### ISSUE TITLE
WinUI TextBox control Language property is not working

### ISSUE THREAD

**Issue by ssaran046** [microsoft/WindowsAppSDK#1043]
**Describe the bug**

TextBox control Language property is not working.

**Steps to reproduce the bug**

1. Create a simple sample with TextBox
2. Set Langauge as "ar-SA"

**Expected behavior**

Arabic language should be applied.

**Screenshots**

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by riverar** [comment]
I don't understand, your issue was transferred to the right place, you closed the issue, then re-opened it here + created a discussion? Is this a spam bot @andrewleader?

**Comment by andrewleader** [comment]
@riverar GitHub doesn't do a great job handling transferred issues (and the fact that we have two separate repos makes things confusing). I suspect what happened is ssaran returned to our repo and couldn't find his issue (and didn't realize it was transferred) so re-created it. It's pretty confusing to not find something you created in a repo when you return a couple days later.

@ssaran046 the bug in the WinUI (microsoft-ui-xaml) is the correct bug, we transferred yours there since it's a WinUI bug. We'll close this issue.
