### ISSUE TITLE
Unhandled exception when Working with List

### ISSUE THREAD

**Issue by ghost1372** [microsoft/WindowsAppSDK#1110]
**Describe the bug**
i want to remove items from a List but i get Unhandled exception

`Unhandled exception at 0x76205ED2 (combase.dll) in HandySub.exe: 0xC0000602:  A fail fast exception occurred. Exception handlers will not be invoked and the process will be terminated immediately.
`
**Steps to reproduce the bug**

```
private List<string> _history = new List<string>();
        public List<string> History
        {
            get => _history;
            set
            {
                _history = value;
                NotifyPropertyChanged(nameof(History));
            }
        }

History.Clear();
//OR
History.RemoveAt(myListView.SelectedIndex);
```
**Expected behavior**

Remove items without problem
**Screenshots**

**Version Info**

0.8.1
NuGet package version: 

Microsoft.WindowsAppSDK 0.8.1

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by btueffers** [comment]
Is this a Windows App SDK specific issue that there are more details for? If not, we can forward the issue internally.

**Comment by ghost1372** [comment]
What do you mean by windows app sdk specific? I see this error when working with windows app sdk application (winui 3), if you need extra info let me know

**Comment by andrewleader** [comment]
Hi @ghost1372, I can't reproduce your error, I think we'll need a full code sample. Could you share both your full XAML page and your full xaml.cs code-behind page?

Also, one tip... if you're binding the History list to a XAML ListView and you're expecting to see the item removed when you remove it from the list, **you need to use an `ObservableCollection<string>`** instead of `List<string>`. ObservableCollections will send out change events when items are removed or cleared, allowing the UI views like ListView to simultaneously remove the item from the UI (or display a new item when a new item is added).

**Comment by ghost1372** [comment]
The behavior is very strange, I created a new project and there was no problem 
I also replaced the List with ObservableCollection in my project and the problems I had were fixed

**Comment by ghost1372** [comment]
it seems that some of this issues is related to visual studio debugger, i can run my app without vs (from start menu in windows) and my app works faster and without problems
