### ISSUE TITLE
Items cant be removed from List/Observablecollections

### ISSUE THREAD

**Issue by ghost1372** [microsoft/WindowsAppSDK#1154]
**Describe the bug**

i want to remove an item from list/Observablecollections, but it does not work and item exist in list,There is also no error except that in visual studio debugger i can see that **System.Collections.Generic.List<T>.Remove returned  false** 

**Steps to reproduce the bug**

please see this project
[App13.zip](https://github.com/microsoft/WindowsAppSDK/files/6911202/App13.zip)

**Expected behavior**

item should be removed from list

**Screenshots**

**Version Info**

[Microsoft.WindowsAppSDK 0.8.1]
 
NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by ghost1372** [comment]
After some research, I realized that the following code solves the problem
```
var currentItem = favorites.Where(item => item.Key.Equals(favorite.Key));
favorites.Remove(currentItem.SingleOrDefault());

```
But it is still not possible to delete item from list in this way:
`favorites.Remove(favorite);
`

**Comment by andrewleader** [comment]
Hey @ghost1372, this looks like a general coding question/problem and not related to WinAppSDK, so I'll close this issue but I'll try to help you get your code working 😊

It looks like you're trying to build an app that has a list of favorites users can add and remove from, and this list of favorites is stored in a file so that the favorites are still there after the user closes and re-opens the file.

It looks like **the problem** is that you're re-creating the list of items (and re-creating instances of each item), and so when you're trying to remove the item, **it's a different instance than the items in your list.**

One topic you might want to research some is **object oriented programming**. Essentially, when you're calling

```csharp
favorites = JsonConvert.DeserializeObject<List<FavoriteKeyModel>>(json);
```

This creates a NEW list with NEW separate instances of objects. Sure, the objects themselves have the same *data*, but they're separate **instances**.

When you create a NEW instance with the code below and then try to remove it...

```csharp
var value = new FavoriteKeyModel { Key = "key1", Server = Server.Server1, Title = "title", Value = "value" };
favorites.Remove(value);
```

the `value` is a separate instance. The `Remove` API compares by instance to find an object referring to the same reference/instance. It doesn't compare via the properties of each object.

That's why when you instead first *find* the instance in the existing list and then pass that item to the Remove API, it works.

```csharp
var currentItem = favorites.Where(item => item.Key.Equals(favorite.Key));
favorites.Remove(currentItem.SingleOrDefault());
```

**Comment by ghost1372** [comment]
Thanks, I understand now
