### ISSUE TITLE
High cpu and memory consumption in UWP app

### ISSUE THREAD

**Issue by HppZ** [microsoft/WindowsAppSDK#1180]
**Screenshots**

![image](https://user-images.githubusercontent.com/12285582/128351234-2206b8ef-b987-4556-bd12-fd9aa2787914.png)
![image](https://user-images.githubusercontent.com/12285582/128351167-b4b44965-057c-4675-9ce4-22d55ae7da76.png)
![image](https://user-images.githubusercontent.com/12285582/128352909-25ba9f28-da7a-49de-88dc-0ee5858368ac.png)
![image](https://user-images.githubusercontent.com/12285582/128353996-a7832087-75e5-4208-90d8-ad9666d7bedd.png)

**Comment by HppZ** [comment]
Windows 19042.985
I have full dump, if you need...

**Comment by btueffers** [comment]
Thank you for reporting this! Please file an issue via Feedback hub since this doesn't seem to be related to the Windows App SDK.

**Comment by riverar** [comment]
@btueffers When shuffling people off to Feedback Hub, it's critical that you tell them where to file feedback to trigger the correct on-demand traces. Where do you suggest they file this particular class of problem?

**Comment by HppZ** [comment]
why this is not a UWP issue?

**Comment by HppZ** [comment]
hello?

**Comment by andrewleader** [comment]
Hi @HppZ, we said this is not a **Windows App SDK** issue. This **is** a UWP issue, which is why we're asking you to file an issue via Feedback Hub.

1. Open Start and launch "Feedback Hub"
2. Click "Report a problem"
3. Enter your title/description
4. For category, select **Developer platform** -> **All other issues**
5. Start a recording reproducing the problem, and submit the feedback!
