### ISSUE TITLE
Introduce std::optional<ChannelDetails> on CreateChannelWithRemoteIdHelper

### ISSUE THREAD

**Issue by danielayala94** [microsoft/WindowsAppSDK#1365]
Comment from @jonwis on #1290, about using std::options<ChannelDetails> instead of a ChannelDetails out param:

Should this method be returning a std::optional<ChannelDetails> instead of using an out-reference-param and returning an hresult?

**Comment by pmpurifoy** [comment]
It is recommended to use optional when you have object and a binary true/false if it was created. https://en.cppreference.com/w/cpp/utility/optional

But in this case, we need to have two failure cases which need to be separated. So we would have to return a std::pair<ChannelDetails, HRESULT> instead of optional (optimized std::pair<ChannelDetails, bool>). It's probably best to use the out-ref param and return HRESULT.

**Comment by pmpurifoy** [comment]
Closing this because of the reason "two failure cases which need to be separated" and treated differently.
