### ISSUE TITLE
[AppLifeCycle] Normal use-case of AppInstance.RedirectActivationToAsync will assert in debug

### ISSUE THREAD

**Issue by MarkIngramUK** [microsoft/WindowsAppSDK#1371]
Following the documentation here - https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/applifecycle/applifecycle-instancing

When a compatible `AppInstance` has been found that we want to redirect to, we call `instance.RedirectActivationToAsync(activationArgs).get();`

The `.get()` at the end makes sense, we're switching to another app, and about to close the current instance down (though I appreciate for Win32, the app could continue running if it wanted).

However, the following assert is triggered:
```
inline void check_sta_blocking_wait() noexcept
{
    // Note: A blocking wait on the UI thread for an asynchronous operation can cause a deadlock.
    // See https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/concurrency#block-the-calling-thread
    WINRT_ASSERT(!is_sta_thread());
}
```

By the functions `get()` => `wait_get(const Async&)` => `check_sta_blocking_wait()`.

Is there any way to work around this? Is waiting on the main thread for the redirection acceptable in this case? If it is acceptable, then is the assert unnecessary?

**Comment by aeloros** [comment]
This assert is indicating there is a bug in the calling code.  Waiting like this on a Single Threaded Apartment causes deadlocks.

**Comment by MarkIngramUK** [comment]
@aeloros it's not going to cause a deadlock because the current app instance is going to close after redirecting to the original instance. 

As I mentioned at the top of the post, I'm following the documentation, which uses that function as an example. Is the documentation / example wrong? What's the correct way of doing this without triggering the assert?

**Comment by andreww-msft** [comment]
Hi Mark

I'm actually in the process of building a bunch of new samples that exercise all the AppLifecycle sets of APIs, and I'll post those soon. Also, I'll work on updating the docs to use snippets from those same samples, so that everything ties up nicely.

Apart from that, I believe aeloros is correct, we're not expecting you to be doing this in an STA. Is there a particular reason why you need this context, I'm just curious?

Thanks
Andrew

**Comment by MarkIngramUK** [comment]
@andreww-msft , this is to enable a single-instance application. When the second instance starts, it redirects, then immediately exits. This is why calling `instance.RedirectActivationToAsync(activationArgs).get();` is convenient, I'm going to be exiting the second instance immediately afterwards, so I don't care if the main thread of the second instance is temporarily blocked.

**Comment by aeloros** [comment]
Hi Mark, calling .get() does a wait that blocks the entire apartment.  This is not a safe way to wait for completion of an async operation.  Search for the 'wait_for' method in our documentation to show how to properly wait here.

https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency-2

**Comment by MarkIngramUK** [comment]
Hi @aeloros , thanks for the link. Is it really an issue if the current process is going to terminate immediately afterwards? `wait_for` looks like it'll only wait for a period of time before returning. I'm attempting to prevent a second launch of our application, and I just want to redirect all of the second app instance activation args to the original app instance.

**Comment by aeloros** [comment]
It could be an issue.  .get() does the equivalent of a WaitForSingleObject() which blocks the thread completely.  There are mechanisms in WinRT, COM, and async programming in general that could need to respond during that time.  If waiting is done correctly then they are not blocked.  That assert is a general assert added to all C++/WinRT Async calls, because it is almost never correct to block like that.

As for the timeout value though, is it truly acceptable to wait infinitely?  Think about what that means to the user.  My suggestion would be to come up with what you think is an acceptable user experience when waiting for one of these redirections.  If it hasn't returned, then an error message might be more useful than a hung application.

**Comment by MarkIngramUK** [comment]
Thanks @aeloros , that's interesting. We only use this route for passing file paths from Explorer currently, so the user experience would be that double clicking a file in Explorer would appear to "not work", and there would be an additional `myapp.exe` listed in Task Manager which is just sat there, hung. Perhaps we could improve that by showing an error message to the user ("Could not open file ..."). It just feels like `wait_for` requires an arbitrary amount of time before reporting an error. How long do I expect the switch to original app instance to take? 1s? 5s?

For reference, this is a copy & paste of our current `WinMain` (with some class name tweaks and additional comments...):

```
int WINAPI wWinMain(HINSTANCE instance, HINSTANCE, PWSTR, int)
{
	if (MyApp::SwitchToSingleInstance())
	{
		// Successfully switched to the original running instance, so we can now terminate
		return 0;
	}

	// We only get here if we're the original instance
	return MyApp(instance).Run();
}

bool MyApp::SwitchToSingleInstance()
{
	using namespace winrt::Microsoft::Windows::AppLifecycle;

	AppActivationArguments activationArgs = AppInstance::GetCurrent().GetActivatedEventArgs();

	auto instances = AppInstance::GetInstances();

	bool switched = false;
	for (AppInstance instance : instances)
	{
		if (instance.Key() == L"myApp")
		{
			switched = true;
			// Note: This will assert, because we're waiting for an async operation on the main thread. 
			instance.RedirectActivationToAsync(activationArgs).get();
			break;
		}
	}

	if (!switched)
	{
		AppInstance::FindOrRegisterForKey(L"myApp");
	}

	return switched;
}

```

**Comment by aeloros** [comment]
It turns out wait_for isn't the solution you need after all anyway.  I misread details about it when replying to you.  Sorry about that.

Andrew and I are working with others to get a proper solution to the problem and have it integrated I to the samples.



Sent from Outlook<http://aka.ms/weboutlook>

________________________________
