### ISSUE TITLE
Global shortcuts for UWP apps

### ISSUE THREAD

**Issue by MarcAnt01** [microsoft/WindowsAppSDK#159]
Snip and Sketch uses Win + Shift + S and is a UWP app, but it does that Windows side. I'd like to use the same capability for my UWP app.

# Proposal: [Global shortcuts for UWP apps] 

## Summary

Shortcuts like Win + Shift + Letter or just Win + Letter could be used by UWP apps.

## Rationale

* I shouldn't be forced to use Desktop Bridge or a Win32 application just for this side feature

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |

## Important Notes

Api proposal

**Comment by Jaiganeshkumaran** [comment]
First of all apps must declare the shortcut in the manifest not by registering and runtime. Also apps must not use the Windows key. Instead the should use any other key. Users must be able to disable global shortcuts for all UWP apps from Windows Settings.

**Comment by ShankarBUS** [comment]
@Jaiganeshkumaran,

Windows settings? That will require change in the OS! And won't be backward compatible.

IMO, the app must be able to register hotkeys at runtime, so that the Devs can provide a way for the users to customise them.

Windows settings could be used to just disable all global shortcuts for a particular app.

Imagine an app like PowerToys using Windows settings to register/modify global hotkeys, no one would like going to settings just for this.

**Comment by maxkatz6** [comment]
I believe safe way to implement will require changes in the OS in any way.
Even if application will ask user to confirm specific keys chosen in runtime, it will not work without changes in the OS (or it could be managed by WinUI layer, that isn't really safe).
In worst case app can listen for any keyboard signals.

PowerToys can require special restricted capability to handle any shortcuts. (again, OS changes)

**Comment by ShankarBUS** [comment]
@Jaiganeshkumaran, @maxkatz6

So you two believe that using the settings will be the safest way for global shortcuts.

But if these changes are made in say next Windows release, they won't be available on older windows versions. Which makes the shortcuts useless on older versions.

I too think that'll be the safest and organized way (and will be similar to notifications, privacy, devices & sensors access, storage access, file integration & etc). But it won't available on older versions anyways.

At least for win32 apps, it should be possible like what I said.

**Comment by Jaiganeshkumaran** [comment]
@ShankarBUS No it's not needed. Global shortcuts aren't really required. Microsoft can make it a new feature in the next update.

**Comment by MarcAnt01** [comment]
> First of all apps must declare the shortcut in the manifest not by registering and runtime. Also apps must not use the Windows key. Instead the should use any other key. Users must be able to disable global shortcuts for all UWP apps from Windows Settings.

Win32 apps can use it, so I think it's a good choice to reach feature parity, otherwise devs will continue to prefer to use Win32 like it's been happening for years just because uwp is too limited

**Comment by Jaiganeshkumaran** [comment]
@MarcAnt01 That doesn't mean UWP should become just like Win32. Everything should be done with user security in mind and that's why UWP exists.

**Comment by MarcAnt01** [comment]
What's the risk of using a global shortcut?
I don't wanna flame, but the restriction for "privacy" are moving away devs from uwp, when building a uwp app (main target now is Desktop), having to deal constantly with restrictions is discouraging. If MS doesn't at least try to make the platform closer to Win32, the situation isn't going to change any time soon. It isn't 2015 any longer when restrictions could be justified by the multiplatform nature of the framework.

**Comment by Jaiganeshkumaran** [comment]
@MarcAnt01 Privacy is really important. Global shortcut has a lot of potentials for misuse so it should be handled with care. Developers should focus on privacy to be future proof.

**Comment by MarcAnt01** [comment]
@Jaiganeshkumaran you still haven't explained the potential risks

**Comment by Jaiganeshkumaran** [comment]
@MarcAnt01 First apps can replace built-in key shortcuts

**Comment by MarcAnt01** [comment]
That's a good point, but:
- UWP apps are going to be distributing through the store, since deploying them is a horrible choice;
- I think built-in shortcuts shouldn't be replaced, there should be a list of available ones

**Comment by MarcAnt01** [comment]
Only big companies can afford the prices, in fact just Adobe does that, so it isn't a problem in my opinion

**Comment by stevewri** [comment]
I want to make sure I understand the ask. Windows allows apps, once they've been launched, to programmatically declare shortcuts or accelerators that invoke specific application actions, but that's different. The ask here is for apps to register (via manifest) something that will cause the shell to launch that app, correct?

And then, per the discussion, consider issues such as:
1) Should an app be able to "take over" a system default global shortcut, w/ or w/o user permission? Security & privacy issues
2) Should an app be able to "take over" another app's global shortcut, w/ or w/o user permission? Similar issues
3) Deprecate legacy mechanisms Win32 apps use to achieve similar results?

**Comment by Jaiganeshkumaran** [comment]
@stevewri Yes apps shouldn't register after they have been launched. Instead they should add the them to the manifest and when the user presses the hotkey the shell should launch that app with the arguments given in the manifest.

1. Should an app be able to "take over" a system default global shortcut, w/ or w/o user permission? Never unless that app replaces the shell. Custom shells are possible in Win32 and UWP
2. Should an app be able to "take over" another app's global shortcut, w/ or w/o user permission? Since it's declared in the manifest, Windows should show a dialog to select the app that the user wants
3. Deprecate legacy mechanisms Win32 apps use to achieve similar results? Should be done

**Comment by MarcAnt01** [comment]
@stevenbrix 
1. No the app shouldn't replace system shortcuts;
2. Let the user select the preferred shortcut;
3. Yeah, I think the behavior should be made consistent.

**Comment by Jaiganeshkumaran** [comment]
Anything that starts with the Windows key should not be allowed

**Comment by MarcAnt01** [comment]
I don't agree on this point, Windows shortcuts should be made available also for third-party apps

**Comment by Jaiganeshkumaran** [comment]
@MarcAnt01 Apps can have Windows key shortcuts inside their app but not global. Only Windows stuff should use a Windows key shortcut.

**Comment by xyzzer** [comment]
[`RegisterHotKey` ](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey) (and [`UnregisterHotKey`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-unregisterhotkey)) is the Win32 hot key API. I'm not sure if it's available to Store apps, but I think it might be. 

One problem with it though is that I think it **requires a running process**, so while Win32 apps could run hidden, perhaps with a tray icon, for UWAs it would be a bit problematic, especially that they can be suspended any time. Having a way to register a hot key in the system for current user session to activate the app with information about the hot key used would be quite powerful. 

IIRC, the Win32 API fails if the hot key combo had already been registered leading to **race condition problems** when multiple apps try to use the same hot key. A **hot key owner picker** similar to protocol handler or file type handler pickers could be used **by default** to solve a problem with an app trying to register a hot key that had already been registered before. It could possibly even be used with the old Win32 API. It would be helpful if an app could also **detect if one or more of the hot keys it tries to register are already taken** without triggering the picker in order to show some UI to the user to disable or change the hot keys that are already taken by other apps before registering them.

Perhaps the OS could provide an API to register multiple hot keys and provide shared UI to change the combinations, pick which app owns which hot key, what to override it with etc. An app would have to provide a description of each hot key and then be notified whether the suggested combination was overridden or turned off in the picker.

There's a lot that could be done, but it would probably all need to be done in the OS.

**Comment by Jaiganeshkumaran** [comment]
@xyzzer Since UWP apps can be suspended anytime, it could be brokered and Windows could resume the app when the hokey is activated. However normally since foreground apps are suspended when you switch to another app, it's not a good idea to automatically switch back and resume the minimized suspended app. It could be handled by a background task instead

**Comment by zakius** [comment]
Global hotkeys, in one form or another, are a necessity: currently I'm using AHK to toggle windows of 3 persistent Store installed apps (that aren't actually UWP and all of them have ability to do it themselves but could make use of the new API)

While it may be a good idea to expose all UWP ones in central places to avoid collisions (like newer variants of WebExtensions API do with Commands) it still will interfere with classic apps and it can't be avoided and I believe we have to just accept it this way. Besides that that central hotkey config would allow us to personalize built in Windows hotkeys + handle some new ones (like the before mentioned window toggle that probably should be handled by window manager itself, not apps)

And out of curiosity, how are shortcut hotkeys exactly handled internally? Probably Explorer registers them somehow so these would end up on the list too so only keyboard hooks would end up missing

**Comment by btueffers** [comment]
Hi everyone, as [announced](https://github.com/microsoft/WindowsAppSDK/discussions/1615), the Windows App SDK is focusing on desktop-based project types and we're working on making it easy to [migrate](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/overall-migration-strategy) from UWP to desktop, which will provide you the ability to use global shortcuts!

If you want additional features in global shortcuts please tell us on our [productboard portal](https://portal.productboard.com/winappsdk/1-windows-app-sdk)!
