### ISSUE TITLE
AppWindow.IsVisible should be settable

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/WindowsAppSDK#1733]
Unlike UWP, you can hide the window programmatically. Instead of a separate AppWindow.Hide method, why not make IsVisible settable?

**Comment by andrewleader** [comment]
Hey @rkarman, any thoughts on whether `AppWindow.IsVisible` property should be settable rather than a separate `Hide()` method?

**Comment by seven-mile** [comment]
Currently the methods naming of AppWindow is very strange, I prefer to unifying all of those functionalities with only properties or only direct getters and setters.

**Comment by rkarman** [comment]
This is great feedback and we will take this into consideration for future APIs, but the current one sticks as is. Breaking changes within a major release is not something we generally want to take on. There are also reasons for not having settable properties for everything on the AppWindow level - some changes to a window may have side-effects (or even be rejected), thus warranting a method for initiating the change and an observable property that lets you know what the current state is.

Since we are not going to change this particular method into a property I will close this issue. Please file a Productboard issue for the more generic "revisit AppWindow API names" if you feel strongly about this issue in order to get upvotes/comments from the community and a potential rework in a future major release.
