### ISSUE TITLE
Product Board missing 1.0 features from roadmap

### ISSUE THREAD

**Issue by riverar** [microsoft/WindowsAppSDK#1781]
Per announcement, Product Board has replaced the Windows App SDK roadmap documentation. But Product Board is missing [previously listed 1.0 features](https://github.com/microsoft/WindowsAppSDK/blob/v1.0.0-preview3/docs/roadmap.md), which may lead to confusion, panic, and/or volcanoes.

Product Board currently shows 8 items as landing for 1.0:
![image](https://user-images.githubusercontent.com/475132/141387804-a845f6f3-f322-4abe-850f-d67c8b7d6f43.png)

* Unpackaged app support
* Windowing APIs
* Activation APIs
* Single/multi-instancing API
* Power State Notifications
* Single project MSIX
* Project templates
* Single NuGet package

Observe none of these items make a distinction between *unpackaged* and *packaged* apps.

Attempting to associate Product Board items to previously documented roadmap items results in the following mapping:

* Unpackaged app support -> ?
* Windowing APIs -> Windowing
* Activation APIs -> App lifecycle
* Single/multi-instancing API -> App lifecycle
* Power State Notifications -> Power state notifications
* Single project MSIX -> Single-project MSIX
* Project templates -> ?
* Single NuGet package -> ?

The following items are missing from Product Board (previously on the roadmap):
* WinUI 3
* Text rendering
* Resource management
* Framework-dependent deployment

**Comment by andrewleader** [comment]
Thanks @riverar for the feedback.

In 1.0, the packaged and unpackaged features are supported equally (aside from [XAML Hot Reload and Live Visual Tree](https://portal.productboard.com/winappsdk/1-windows-app-sdk/c/43-xaml-hot-reload-live-visual-tree-works-with-unpackaged-winui-3-apps)) so we're removing the distinction between what's supported in packaged vs unpackaged.

WinUI 3 is listed in the [Released tab](https://portal.productboard.com/winappsdk/1-windows-app-sdk/tabs/6-released) under 0.5, and expanding that to support unpackaged is what the 1.0 "Unpackaged app support" item covers.

Same with text rendering, that's in the [Released tab](https://portal.productboard.com/winappsdk/1-windows-app-sdk/tabs/6-released) for 0.5 since that's when it was released (and didn't have unpackaged support), under the name DWriteCore (I'm going to update the name to be the friendly name we use in docs).

I'll add resource management to 0.5.

For framework-dependent deployment, that's also a 0.5 feature and given it's so fundamental and low-level, I'm not sure that's worth putting on there. The feature some developers are interested in going forward is [self-contained deployment](https://portal.productboard.com/winappsdk/1-windows-app-sdk/c/42-self-contained-xcopy-deployment-support), which is in the Under Consideration tab.

**Comment by riverar** [comment]
@andrewleader Thanks, I missed the items on the Released tab!
