### ISSUE TITLE
How to disable rounded window corners for a UWP app in Windows 11

### ISSUE THREAD

**Issue by benstevens48** [microsoft/WindowsAppSDK#1838]
I have a UWP app which is a photo viewer, and I do not want rounded window corners because then the corner of the photo is clipped (depending on window aspect ratio and zoom level etc) and I want it to provide a pixel perfect view of the image (since the app may be used for serious purposes). Is there any way to disable the window corner rounding on Windows 11? If not, I strongly suggest there should be. Ideally I would want to be able to provide it as an option in my app that users could change.

**Comment by riverar** [comment]
@benstevens48 You can [call DwmSetWindowAttribute](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/apply-rounded-corners?WT.mc_id=WD-MVP-5002756#api-definition) with a `DWM_WINDOW_CORNER_PREFERENCE` of `DWMWCP_DONOTROUND`.

**Comment by benstevens48** [comment]
@riverar - thanks, but yes, this is a pure UWP app. 

Well I wanted to ask here because my suspicion is that it's not possible, in which case I want to suggest it somewhere where it could actually have a chance of being seen by the right people. So is it the policy that this repo no longer takes any questions or feedback on UWP? I was under the impression that WinUI is part of Windows App SDK, and WinUI includes active development on WinUI 2, which is based on in-box UWP. Perhaps WinUI would be a better place for this question/suggestion?

**Comment by riverar** [comment]
@benstevens48 Fair. And I agree, filing an issue on [WinUI](https://github.com/microsoft/microsoft-ui-xaml/issues) makes sense. That might sit for a while though.

The workflow I'd go down:
1. Investigate getting an instance of ICoreWindowInterop for your CoreWindow and try calling DwmSetWindowAttribute. It might Just Work™️.
2. If that fails, consider adding a full-trust component to your UWP app to call DwmSetWindowAttribute for you. Skimming over @stefanwickdev's past work may be a great starting point (https://github.com/StefanWickDev/UWP-FullTrust).

Hope that helps / good luck!

**Comment by andrewleader** [comment]
Hey @benstevens48, thanks for trying to understand where to submit feedback! I'll try to clarify some things 😊 (I'm one of the program managers at Microsoft that works on Windows App SDK).

WinUI **\*3\*** is part of the Windows App SDK, however WinUI 2 is not. WinUI 2 is the version of WinUI that supports UWP, WinUI 3 is the version of WinUI that supports desktop apps. Windows App SDK itself only supports a migration path from UWP to desktop projects so that you can use Windows App SDK features, Windows App SDK doesn't support UWP project types or adding new UWP features.

For UWP questions, you can use...

* [Microsoft Q&A windows-uwp tag](https://docs.microsoft.com/en-us/answers/topics/46321/windows-uwp.html): We have dedicated support staff that helps answer questions there
* [Stackoverflow](https://stackoverflow.com/questions/tagged/uwp) as Rafael mentioned
* [UWP Community Discord](https://discord.com/invite/uwp) as Rafael mentioned

For UWP feature requests...

* The WinUI 2 team uses [their XAML repository](https://github.com/microsoft/microsoft-ui-xaml).
* The rest of the UWP team uses [Feedback Hub](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332), in the "Developer Platform" category.

I'm not sure whether these windowing properties are something the XAML / WinUI 2 team owns or whether another UWP team owns that. As Rafael suggested, you could file an issue on the WinUI 2 team's repository.

I'll close this issue since it's not Windows App SDK related, however feel free to keep discussing while it's closed if you'd like!

**Comment by benstevens48** [comment]
@riverar - thanks for the suggestions. I started looking at 1, but ICoreWindowInterop is in the Desktop partition. I don't really want to try and hack access to this. I also don't want to add a full-trust component because it adds quite a bit of extra complication and makes my years of trying to conform to the AppContainer model seem kind of pointless (although I guess I will ditch it anyway when I eventually migrate to WinUI3).

**Comment by danielkornev** [comment]
If one uses AppWindow, how to remove Rounded Window Corners in such UWP App?
