### ISSUE TITLE
Packaged WinUI app can not be installed on ARM64

### ISSUE THREAD

**Issue by nxtn-staged** [microsoft/WindowsAppSDK#1862]
### Describe the bug

WinUI 2 in UWP or WinUI 3 in desktop app packages created for ARM64 contain dependencies for ARM that can't be installed.

### Steps to reproduce the bug

1. Create a **Blank App, Packaged with Windows Application Packaging Project (WinUI 3 in Desktop)** project.
2. **Project** > **Publish** > **Create App Packages...**
3. Select **Sideloading**.
4. Select **ARM64**.
5. Install the created app package by running *Install.ps1*.

```
Found bundle: \Test.WinUI (Package)_1.0.0.0_Debug_Test\Test.WinUI (Package)_1.0.0.0_arm64_Debug.msixbundle
Installing app...
Found dependency package(s):
\Test.WinUI (Package)_1.0.0.0_Debug_Test\Dependencies\x86\Microsoft.VCLibs.x86.Debug.14.00.appx
\Test.WinUI (Package)_1.0.0.0_Debug_Test\Dependencies\x86\Microsoft.VCLibs.x86.Debug.14.00.Desktop.appx
\Test.WinUI (Package)_1.0.0.0_Debug_Test\Dependencies\x86\Microsoft.WindowsAppRuntime.1.0.msix
\Test.WinUI (Package)_1.0.0.0_Debug_Test\Dependencies\arm\Microsoft.VCLibs.ARM.Debug.14.00.appx
\Test.WinUI (Package)_1.0.0.0_Debug_Test\Dependencies\arm\Microsoft.VCLibs.ARM.Debug.14.00.Desktop.appx
\Test.WinUI (Package)_1.0.0.0_Debug_Test\Dependencies\arm64\Microsoft.VCLibs.ARM64.Debug.14.00.appx
\Test.WinUI (Package)_1.0.0.0_Debug_Test\Dependencies\arm64\Microsoft.WindowsAppRuntime.1.0.msix
Add-AppxPackage : Deployment failed with HRESULT: 0x80073D10, The deployment operation failed because the package targets the wrong processor architecture.

Windows cannot install package Microsoft.VCLibs.140.00.Debug because the package requires architecture ARM, but this computer has architecture ARM64.
```

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 (22000)

### IDE

Visual Studio 2022

**Comment by Scottj1s** [comment]
This issue is not unique to the Windows App SDK, but is a problem with the Add-AppDevPackage.ps1 generated by the app packaging logic.  This script is invoked by install.ps1, and explicitly attempts to install arm dependencies on an arm64 device:
line 467:
`        if (($ProcessorArchitecture -eq "arm" -or $ProcessorArchitecture -eq "arm64") -and (Test-Path (Join-Path $DependencyPackagesDir "arm")))`

You can work around this in two ways:

- avoid the install.ps1 script and instead install the msixbundle directly on the target device, along with any arch-specific dependencies
- as others have done, delete the arm dependency folder so that Add-AppDevPackage.ps1 doesn't find it and attempt to install it


I would also recommend opening a [Visual Studio bug](https://developercommunity.visualstudio.com/home).  Note that the site is currently experiencing network errors.
