### ISSUE TITLE
Windows App SDK 1.0.1 violates semver, ships new feature

### ISSUE THREAD

**Issue by riverar** [microsoft/WindowsAppSDK#2287]
The team just shipped Windows App SDK 1.0.1 and [added multi-windowing](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#new-features), breaking [documented/agreed upon version number expectations](https://github.com/microsoft/WindowsAppSDK/discussions/637).

[Semantic versioning](https://semver.org) sets forth:
> Given a version number MAJOR.MINOR.PATCH, increment the:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards compatible manner, and
> - PATCH version when you make backwards compatible bug fixes.

So using that as a rubric, this new release should have been versioned **1.1** not **1.0.1**.

Violating these principles (and trust) is a big deal and should be taken seriously. Developers may have dependency graphs configured in such a way to exclude pulling down releases with new features, opting for safer bugfix only releases.

**Comment by marb2000** [comment]
We evaluated the backport of the multi-window feature and considered it as a bug fix because there aren't new APIs and the framework was throwing an exception when you try to create an additional window.  Most of the work was about stabilizing the feature in many scenarios. Actually it;'s not even a backport because 1.1 is not released yet, but we, badly, it's a backport because it was planned for 1.1 and the bug fixes were in the 1.1 branch.

**Comment by riverar** [comment]
Thanks for the quick response / background!

I don't agree with the decision that was made though. By the stated logic, the team could probably convince themselves that stuffing _admin elevation_ and _xcopy deployment_ into a patch release is okay too.

My understanding is that folks download patch-only releases to minimize the risk of code churn breaking their app as much as possible. Hopefully this new multi-window feature is fairly siloed and won't introduce more bugs!

You're welcome to close this issue, no action needed here. Look forward to continued discussions at MVP summit.
