### ISSUE TITLE
Caption button in title bar Not clickable when ExtendContentintoTitlebar is given true

### ISSUE THREAD

**Issue by vishal2447** [microsoft/WindowsAppSDK#2342]
### Describe the bug

The caption buttons are not clickable when the window is maximized. It works when the window is opened , it stops working after being maximized .

### Steps to reproduce the bug

1.When activating a window set ExtendContentintoTitlebar  property to true then activate  the window 
2. After the window is opened maximize the window the caption buttons are not clickable

### Expected behavior

The caption button to work  even after maximizing the window

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022

### Additional context

Nuget version 1.01

**Comment by mevey** [comment]
Hello @vishal2447,
You need to check if [title bar customization](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.windowing.appwindowtitlebar.iscustomizationsupported?view=windows-app-sdk-1.0#microsoft-ui-windowing-appwindowtitlebar-iscustomizationsupported) is supported before calling AppWindowTitleBar.ExtendsContentIntoTitleBar. The reason for that is because titlebar customization with WinAppSDK windowing APIs only works on Win11+. [See more here.](https://docs.microsoft.com/en-us/windows/apps/develop/title-bar?tabs=wasdk)

**Comment by vishal2447** [comment]
Will these APIs be supported for Windows 10 in future?

**Comment by vishal2447** [comment]
m_window = new MainWindow();
m_window.Title = "Main Window";
m_window.ExtendsContentIntoTitleBar = true;

I m using this property for extending the content and not using the AppWindowTitleBar.ExtendsContentIntoTitleBar , Is this property also supported only in WIndows 11?

**Comment by mevey** [comment]
No, WinUI's [Window.ExtendsContentIntoTitleBar](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.window.extendscontentintotitlebar?view=winui-3.0) works on both win10 and win11 and is a good alternative until we are able to bring AppWindowTitleBar API support further downlevel.

**Comment by ahmetaksoy1985** [comment]
Yes ExtendsContentIntoTitleBar works on Windows 10. It was working correctly on WinAppSDK 1.0.0. After WinAppSDK 1.0.1 update Minimize, Maximize, Close buttons clicks but not working on Windows 10.

**Comment by pratikone** [comment]
this should be fixed in both Window custom titlebar as well as AppWindow custom titlebar apis. Both are using the same implementation downlevel.
