### ISSUE TITLE
Can't install Windows App Sdk

### ISSUE THREAD

**Issue by roxxel** [microsoft/WindowsAppSDK#2408]
### Describe the bug

After running installer I get this message:
```
Installing license: WAR_MAINPACKAGE_LICENSE
Install result : 0x0
Deploying package: Microsoft.WindowsAppRuntime.1.0_2.460.358.0_x64__8wekyb3d8bbwe
Package deployment result : 0x80080204 The Appx package's manifest is invalid.
One or more install operations failed. Result: 0x80080204
```

### Steps to reproduce the bug

I don't actually know how to reproduce this bug since I done nothing but ran the installer

### Screenshots

winver: 
<img width="340" alt="image" src="https://user-images.githubusercontent.com/64275777/163691577-4fef8ce5-8d89-42da-8bb4-6172041ceb79.png">

**Comment by DrusTheAxe** [comment]
0x80080204 = APPX_E_INVALID_MANIFEST

That's rather surprising. @sachintaMSFT tag you're it :-)

Do you know the URL you got the installer from? Just to help verify a repro. Thanks

**Comment by roxxel** [comment]
> 
https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads
Here it is

I can provide installer file if needed

**Comment by sachintaMSFT** [comment]
I just tried both 1.0.2 (the exact version you shared from the command line outoput) and it is successfully installing for me on 22598.1 Windows 11 Version. Below is the screenshot from where I installed it from at https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads 
![image](https://user-images.githubusercontent.com/80828309/164119464-323926fb-3598-41cd-b7ec-24b543ec8303.png).

Did you also get the installer from that same link ?

It would be great if you could share %windir%\system32\winevt\logs\Microsoft-Windows-AppXDeploymentServer%4Operational.evtx ?

**Comment by roxxel** [comment]
Sure

[Microsoft-Windows-AppXDeploymentServer%4Operational.zip](https://github.com/microsoft/WindowsAppSDK/files/8518912/Microsoft-Windows-AppXDeploymentServer.4Operational.zip)

**Comment by sachintaMSFT** [comment]
The logs shared don't show 0x80080204 error for any WinAppSDK packages. Either, the logs aren't saved to the disk if the issue is reproduced just before sharing the logs or they are overwritten due to the circular buffer of the evtx file if the issue was hit long back in time.

Could you try the installer again and then run the following command line to flush the logs in memory to disk and share the output files ?
wevtutil epl Microsoft-Windows-AppXDeploymentServer/Operational <Any_Path_OnYourMachine>\Microsoft-Windows-AppXDeploymentServer-Operational.evtx
wevtutil epl Microsoft-Windows-AppxPackaging/Operational <Any_Path_OnYourMachine>\Microsoft-Windows-AppxPackaging-Operational.evtx

Could you also try 1.0.3 release and share the result ?

**Comment by roxxel** [comment]
Now it works, I also encountered issue when installer failed to install because there was application running which uses WindowAppSDK (Edge, Lively Wallpaper) FYI

**Comment by sachintaMSFT** [comment]
It's great to hear that the installer is working for you. Regarding Installer failing due to another dependent application running, it's a known issue in 1.0.* versions. In WinAppSDK 1.1 version to be released, the Installer will have an option to select to force deployment of WinAppSDK packages even if they are running or dependent applications are running.
