### ISSUE TITLE
Question: 为什么我使用Folder Picker选择带文件目录非常慢？

### ISSUE THREAD

**Issue by coidx** [microsoft/WindowsAppSDK#2450]
我对空目录选择非常快，但是我选择一个目里面带有文件的就非常慢。

https://user-images.githubusercontent.com/4701997/165125964-5d02d767-0544-40da-a1f5-b3bf7a1eedc0.mp4

我使用如下代码：
![image](https://user-images.githubusercontent.com/4701997/165126583-f4390a2f-c146-49de-86ed-034f95945a27.png)

WIndows App SDK：1.0.1.69647397

**Comment by Jaiganeshkumaran** [comment]
@coidx 我不明白，你到底想做什么?

**Comment by coidx** [comment]
> @coidx 我不明白，你到底想做什么?

目的：选择图片的导出目录

出现的情况：我选择目录里面带有文件那么await picker.PickSingleFolderAsync(); 会等待很久才会返回。但如果我选择一个空目录就回立即返回

期待情况：不论选择目录是否为空或者是复杂目录都是立即返回

**Comment by Jaiganeshkumaran** [comment]
@coidx Oh, it's slow for the PickSingleFolderAsync method to complete when you're picking a large folder?

**Comment by coidx** [comment]
> @coidx Oh, it's slow for the PickSingleFolderAsync method to complete when you're picking a large folder?

不一定是大目录，而是只要目录不是空的，它就是返回很慢，反之如果是空目录就会立即返回。

**Comment by BenJKuhn** [comment]
I've opened an issue to track this in the Windows OS issue database but am closing this issue since this appears to be an issue with the picker and not app sdk (just going from description). If you'd like to track this issue, please report the problem via feedback hub, and make reference to the issue link below (you won't be able to open, it's internal only, but the feedback recipient will be able to use it).

https://task.ms/39380732

Thanks for reporting this.

Ben
