### ISSUE TITLE
Bootstrapper crashes if a package can't be found.

### ISSUE THREAD

**Issue by dhoehna** [microsoft/WindowsAppSDK#2672]
### Describe the bug

This issue is fixed in 1.1.2.

It would be nice if there was documentation explaining "X will be thrown if the specific package can't be found"

### Steps to reproduce the bug

1. Don't install any Windows App SDK packages.
2. Use the bootstrapper to load Windows App SDK.

### Expected behavior

Really, just some documentation saying "X will happen if the bootstrapper is used and the Windows App SDK framework packages aren't installed"

**Comment by fredemmott** [comment]
This a bug, fixed for 1.2: https://github.com/microsoft/WindowsAppSDK/issues/2592

**Comment by DrusTheAxe** [comment]
You shouldn't get anything 'thrown' on not-found. By default you'll get a MessageBox explaining the problem and what to do about it, or other behavior if you opt-in to certain options. No crash, no exception.

This crash was due to a bug in the NotFound code path introduced in 1.1.0, crashing before reaching the MessageBox(Heyyyyy all...).  This was fixed in #2592 for 1.2 and is in the upcoming 1.1.2 servicing update.
