### ISSUE TITLE
Missing x86 runtimes for WinAppRuntime.Main and WinAppRuntime.Singleton

### ISSUE THREAD

**Issue by loneursid** [microsoft/WindowsAppSDK#2707]
### Describe the bug

The WinAppRuntime.Main and WinAppRuntime.Singleton x86 runtimes are not getting installed on a x64 computer.

It will cause any x86 apps that rely on these services to fail. For example calling AppNotificationsManager.Default.Register(); will faill on an x86 app if WinAppRuntime.Singleton is miising. 

### Steps to reproduce the bug

Remove all WindowsAppSDK packages
Install the latest WindowsAppSDK. (Download from https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads)

Execute: (get-appxpackage micro*win*appruntime*).packagefullname and look at list of installed packages.

Observe: All packages but Main and Singleton will have two entries: one for x86 and one for x64. Main and Singleton only have entries for 64.

### Expected behavior

x86 packages should be available for Main and Singleton.

### NuGet package version

1.1.2

### Packaging type

Unpackaged

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2022

**Comment by DrusTheAxe** [comment]
> The WinAppRuntime.Main and WinAppRuntime.Singleton x86 runtimes are not getting installed on a x64 computer.

ByDesign. Those are main packages (as in, PackageType=main). A user can only have 1 main package in a family registered at a time. Although x86 packages could be applicable to x64 (and arm64) machines given a choice the package matching the machine architecture is the 'best fit'. That's why your x64 machine as the x86 Main+Singleton packages and not the x86 packages.

The(!) Main+Singleton packages registered for a user should suffice to do everything WinAppSDK need regardless of applications' processor architecture.
