### ISSUE TITLE
IconShowOptions.HideIconAndSystemMenu doesn't take effect when AppTitleBar.ExtendsContentIntoTitleBar set to true

### ISSUE THREAD

**Issue by Lightczx** [microsoft/WindowsAppSDK#2823]
### Describe the bug

As described as title, 
```cs
AppWindowTitleBar appTitleBar = appWindow.TitleBar;
appTitleBar.IconShowOptions = IconShowOptions.HideIconAndSystemMenu;
appTitleBar.ExtendsContentIntoTitleBar = true;
```
After doing this, the system menu can still open by right click the drag rectangle.
It seem like the drag area is handling message regardless of the setting.

### Steps to reproduce the bug

Just add some code in a WinUI3 project

```cs
AppWindowTitleBar appTitleBar = appWindow.TitleBar;
appTitleBar.IconShowOptions = IconShowOptions.HideIconAndSystemMenu;
appTitleBar.ExtendsContentIntoTitleBar = true;
```

### Expected behavior

The title bar area should not respond to the mouse right click.

### NuGet package version

1.1.3

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

**Comment by mevey** [comment]
@Lightczx, I see the disconnect here and I'll make sure we make this clearer in documentation.

This  IconShowOptions API affects the window icon and its behavior as it relates to the showing and hiding of the system menu (on the window icon only and not the rest of the title bar surface)

**Comment by riverar** [comment]
@mevey @rkarman Err. Why would a developer want to turn off the system menu via the icon entry point but not others?

**Comment by Lightczx** [comment]
I'm using the subclassing technique to prevent the system menu from showing now.

```c#
switch (uMsg)
{
    case WM_NCRBUTTONDOWN:
    case WM_NCRBUTTONUP:
        {
            return new(0);
        }
}
```


I Suggest making a new API like :
```
AppTitleBar.IsSystemMenuEnabled = false;
```
to simply turn off all system menu on titlebar, even when `ExtendsContentIntoTitleBar = true`.

> Why would a developer want to turn off the system menu via the icon entry point but not others?

The system menu is not consistent with the other UI part, if the menu can adopt the Fluent Design style, I would rather keep it.
Currently it really just a legacy style context menu.

**Comment by riverar** [comment]
@Lightczx Agreed. 👍

**Comment by mevey** [comment]
The system menu is an important menu for all windows users especially those who primarily navigate via keyboard. It's also an accessibility tool for many who need to manipulate their windows with tools like Narrator. If you want your app to be usable and accessible you need to ensure users can find the system menu when they need it. Whether the system menu has a modern design or not because it plays a key role. 

On a single/click or tap, your title bar should show the system menu on any area that does not have interactive content. Where a drag region is defined, a user can click/tap to show the system menu. These two functionalities are tied. The top left corner of a window (where the icon is) is a place users can quickly go to close the window (by double clicking/tapping the icon) or to show the system menu (with a single click or tap).

**Default title bar**
We created the IconShowOptions API to give developers the option of having an icon or not. In the future, if developers needed it, we could add an Enum `HideIconShowSystemMenu` to reserve the top left corner (area that the icon takes) to preserve the double click or right click behavior windows users expect even if the developer does not want to have an icon on their window. We do **not** recommend doing anything to prevent the system menu from showing.

**Custom title bar**
When` ExtendsContentIntoTitleBar = true`, you as an app author gets to determine where you define your drag regions (with SetDragRectangles API) and where a drag region is defined, the system menu shows up on clicking or tapping. We recommend that you define drag regions over your window icon, your window title and all other title bar spaces that do not have interactive content.

**Comment by Lightczx** [comment]
> It's also an accessibility tool for many who need to manipulate their windows with tools like Narrator

I just want the SystemMenu not open when a user use their mouse.
If they use keyboard or narrator, the system menu do need to show. 
A user can alway perform the action describe in the context menu by clicking some buttons, so I don't think there is any accessibility issue in this situation.
As far, I believe most of the users perfer a nice look UI, click buttons at the top-right corner, rather than right click the titlebar, and click the menu items to min/max/restore/close the window.

**Comment by mevey** [comment]
> I just want the SystemMenu not open when a user use their mouse.

Are you able to tell us more about why you don't want this?

> A user can alway perform the action describe in the context menu by clicking some buttons, so I don't think there is any accessibility issue in this situation.
If you mean keyboard shortcuts, not everyone knows them. 


> As far, I believe most of the users perfer a nice look UI, click buttons at the top-right corner, rather than right click the titlebar, and click the menu items to min/max/restore/close the window.

There are users who've come to rely on this. I agree with a nice look UI and Windows will continue to update UI like the stsrem menu.

**Comment by Lightczx** [comment]
> There are users who've come to rely on this. I agree with a nice look UI and Windows will continue to update UI like the system menu.

That‘s why I don't want to show the system menu, the inconsistency of the appearance (or UI) makes me feel a bit annoyed.

And also there is no easy way to control the menu items(add/disable/remove).
For example: Microsoft Edge's system menu have some custom items.
I think AppWindowTitleBar should provide some functionality to the menu customization. Or can we add a new property like `AppWindowTitleBar.SystemMenuCustomItems` to append the menu.
Is that possible?

**Comment by mevey** [comment]
Updating the system menu look is on the roadmap. You'll have to update your code when that happens.

Adding support for custom menu items in the system menu is something we can consider. Do let us know what sort of functionality you'd like to add there by opening a feature request.

Do you feel that we can close on this particular issue? @Lightczx

**Comment by Lightczx** [comment]
Yes, I will open a feature request for that.
