### ISSUE TITLE
`AppInstance.GetActivatedEventArgs` crashes if called before `AppNotificationManager.Register`

### ISSUE THREAD

**Issue by nxtn-staged** [microsoft/WindowsAppSDK#2959]
### Describe the bug

When toast activated from the background, `AppInstance.GetCurrent().GetActivatedEventArgs()` crashes if `AppNotificationManager.Default.Register()` is not called before, because `m_waitHandleForArgs` is not initialized.

https://github.com/microsoft/WindowsAppSDK/blob/f2234048b7beb7eb7216658e6f801fdb70720dfe/dev/AppNotifications/AppNotificationManager.cpp#L96

### Steps to reproduce the bug

1. Follow [Send a local toast notification from C# apps](https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/send-local-toast?tabs=desktop-msix) to set up a packaged app.
2. In `Package.appxmanifest`, replace `-ToastActivated` with `----AppNotificationActivated:`.
3. In the app's startup code, replace `ToastNotificationManagerCompat.OnActivated` with `AppInstance.GetCurrent().GetActivatedEventArgs()`.
4. Click the notification when the app is closed.

### Expected behavior

An exception thrown or anything else better.

### NuGet package version

1.2.220727.1-experimental1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022-preview

**Comment by pmpurifoy** [comment]
This behavior is by design and is the same for both Push/AppNotifications. The activated app must call AppNotificationManager.Default().Register() before calling GetActivatedEventArgs or else the app will crash. 

This should be documented in the [AppNotification Docs](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/notifications/app-notifications/app-notifications-quickstart?tabs=cpp) but it is not mentioned at all.

Specifically, we should add this in the documentation at [Step 3](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/notifications/app-notifications/app-notifications-quickstart?tabs=cpp#step-3-register-to-handle-an-app-notification). 

Regardless of all these things, GetActivatedEventArgs shouldn't throw if the app was activated by App/PushNotifications and the app failed to register. It should just return nullptr.

**Comment by pmpurifoy** [comment]
We need to update our documentation with this pattern. @robertzhou-wpn

**Comment by pmpurifoy** [comment]
I've filed an issue to address the throwing behavior to instead return null args. https://github.com/microsoft/WindowsAppSDK/issues/2961

**Comment by robertzhou-wpn** [comment]
@drewbatgit, can you please help to update the  [AppNotification Docs](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/notifications/app-notifications/app-notifications-quickstart?tabs=cpp)?

**Comment by robertzhou-wpn** [comment]
The doc [AppNotification Docs](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/notifications/app-notifications/app-notifications-quickstart?tabs=cpp) has been updated.
