### ISSUE TITLE
TitleBar display issues with ExtendContentIntoTitleBar

### ISSUE THREAD

**Issue by onslauth** [microsoft/WindowsAppSDK#2987]
### Describe the bug

Setting the TitleBar color to a solid color using the following:
```
<SolidColorBrush x:Key="WindowCaptionBackground">Orange</SolidColorBrush>
```
causes the underlying content to be occluded.

Changing the value to the following solves the issue:
```
<SolidColorBrush x:Key="WindowCaptionBackground">Transparent</SolidColorBrush>
```
however this causes another display issue, with regards to the z-index ordering. The example uses the following layout:
`Window->Grid->NavigationView->Frame->Page->Grid->SplitView->Grid->Canvas`
When dragging the `Image` added to the canvas, it then occludes the TitleBar content.

### Steps to reproduce the bug

Run application.

### Expected behavior

Setting a solid color for the `WindowCaptionBackground` should not occlude the content that has been extended into the TItleBar.
The content of the `NavigationView->Frame` should not occlude the content in the TitleBar. Please see screenshots.

### Screenshots

- `WindowCaptionBackground` set to `Orange`:
![image](https://user-images.githubusercontent.com/44875/191732958-8b14cc8c-472b-42f2-9fe3-bfdfce2ffd38.png)

- `WindowCaptionBackground` set to `Transparent`, you can see the content added to `Navigation.ContentOverlay` clearly visible ( TextBlock with wording "Test" ):
![image](https://user-images.githubusercontent.com/44875/191733827-fdf5b996-eb67-4ca1-b22e-dface330be65.png)

- Content visible in `NavigationView->Frame->...->Canvas`:
![image](https://user-images.githubusercontent.com/44875/191734071-b08898d1-2086-4896-a3bd-200040713daf.png)

- Content in the canvas is moved/dragged:
![image](https://user-images.githubusercontent.com/44875/191734238-0ba90b07-86aa-477e-a496-7fdbb97eda28.png)

### NuGet package version

1.1.4

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 21H1 (19043, May 2021 Update)

### IDE

Visual Studio 2022

### Additional context

Windows App SDK version is 1.1.5, but option was not available in `Nuget package version`.

**Comment by pratikone** [comment]
Hi @onslauth ,  thanks for letting us know. It is a known issue and we no longer suggest doing this way. Setting `WindowCaptionBackground` to Transparent is the way to go. 👍🏾For setting background color, set background color of titlebar element used in `SetTitlebar` and it will not occlude anything.  Hopefully, that will fix the image issue too

MSDN page on SetTitlebar needs a change too. I am doing a overhaul of winui titlebar under the hood design and hence, the docs are not yet touched yet because they will be touched again.

I am closing this this issue. if it doesn't fix it or you have more related questions, feel free to open it again.
