### ISSUE TITLE
Scrolling is less smooth in files preview version than in stable version

### ISSUE THREAD

**Issue by soredake** [microsoft/WindowsAppSDK#3060]
### Describe the bug

Scrolling in [files preview version](https://github.com/files-community/Files) is less smooth than in [files stable version](https://files.community/download/stable). Files devs told me to report this problem here https://github.com/files-community/Files/issues/10205.

### Steps to reproduce the bug

1. Install files preview and stable version.
2. Scroll in stable version (smooth)
3. Scroll in preview version (not smooth)

### Expected behavior

Scroll is smooth in files preview version.

**Comment by ChewWorker** [comment]
There is a bug in WinAppSDK 1.2 regarding high refresh rate monitors and animations/scrolling. It turned out to be particularly tricky to track down/fix, but we believe it's fixed in 1.3. Can you update to 1.3 and see if it still reproes? If it does, we are in a much better position to fix it in 1.3.

Thanks!

**Comment by soredake** [comment]
@ChewWorker i will wait until they update it to 1.3 https://github.com/files-community/Files/blob/main/src/Files.App/Files.App.csproj#L81

**Comment by bpulliam** [comment]
A fix for the core issue is included in the 1.3 release, released April 12th. If you are still seeing low framerates on high refresh monitors using 1.3, please log a new issue, as it is likely a different scenario and we should track it separately.
