### ISSUE TITLE
[MRTCore] Get OSS approval for new binary Microsoft.ApplicationModel.Resources.PriTasks.dll

### ISSUE THREAD

**Issue by rohanp-msft** [microsoft/WindowsAppSDK#307]
This requires multiple steps:
1. Check in the code into the INTERNAL, PRIVATE repo.
2. Make changes to get approved.
3. Check in here.

**Comment by wjk** [comment]
What code is this that you are referring to? From the assembly name, I presume it is MSBuild tooling for generating PRI files.

**Comment by wjk** [comment]
Also: Would this entail releasing the source behind processing the `priconfig.xml` files? Ever since I started doing Desktop Bridge apps circa build 14393, they still remain incomprehensible to me. I have never been able to get them to work right, except when following someone else's tutorial. Thanks!

**Comment by rohanp-msft** [comment]
This work isn't planned anymore. Closing.
