### ISSUE TITLE
How to create a optional package for Windows App SDK?

### ISSUE THREAD

**Issue by Osirisoo0O** [microsoft/WindowsAppSDK#3112]
We have some plugins in our UWP app and we want use them in new WinUI 3 app. 
So anyone knows what can I do ?
Thinks!

**Comment by Osirisoo0O** [comment]
For CsWinRT Component, no help. 
Maybe I need a complate example.

**Comment by DrusTheAxe** [comment]
There are multiple possible solutions. Caveats and tradeoffs depend on more details.

What is a 'plugins' to you? WinRT inproc object? COM? DLL with exports? Non-PE files? Other tech?

Devil's in the details.

**Comment by Osirisoo0O** [comment]
@DrusTheAxe  Just like UWP optional package. A package just work for my application.

**Comment by DrusTheAxe** [comment]
So today you have a UWP app some plugins in a main package?

And you're _changing_ the UWP app to a WinUI3 app and want to continue using the plugins?

Or you're making a _new_ WinUI3 app in a _new_ main package and want the plugins to be in the package? Or you want the plugins to be separate and optionally available to users who have the new main package installed?

Do you want the plugins to be shared available to _both_ apps?

**Comment by Osirisoo0O** [comment]
Yes, I want change the UWP to WinUI3 app. And I want the plugins to be separate and optionally available to users who have the new main package installed. 
I know too little about WinUI3.

**Comment by DrusTheAxe** [comment]
Sorry for the lag, I missed this thread.

Plugins bring 2 needs to the table:

1. Discovery
2. Interaction

The recommended solution for #1 is `<Extension Category="windows.appExtension">`. Your plugins provide your needed metadata about themselves via an appextension in their appxmanifest and you enumerate and retrieve this via [AppExtensionsCatalog](https://learn.microsoft.com/uwp/api/windows.applicationmodel.appextensions.appextensioncatalog?view=winrt-22621) to `.Find*()`, `.Open()` and retrieve their data.

The recommended solution for #2 is to tell developers to implement an OOP WinRT Server, put into a Main package and declare [<uap15:DependencyTarget>true</>](https://learn.microsoft.com//uwp/schemas/appxpackage/uapmanifestschema/element-uap15-dependencytarget). You use the [Win11 Dynamic Dependencies API](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/framework-packages/use-the-dynamic-dependency-api) to add their package to your package graph (TryCreatePackageDependency, etc) and then you use routine WinRT practices to instantiate and interact with their object.

One caveat: that AppExtension support's been around for ages (since RS5 or even earlier) but `<uap15:DependencyTarget>` is new as of 22H2 (aka Sun Valley 2 aka 2022 Update aka 10.0.22621.0). If you need to run on older systems then the recommended answer for #2 is to tell developers to implement a Packaged COM OOP Server and put it into a Main package. Then you use `CoCreateInstance()` and other routine COM practices to instantiate and interact with their object.

There are possible other techniques of course. Windows has a huge palette of technologies and options. But the above is the simplest and most effective solutions, thus the recommendation.
