### ISSUE TITLE
OverlappedPresenter.SetBorderAndTitleBar would not fully eliminate the title bar

### ISSUE THREAD

**Issue by ACGNnsj** [microsoft/WindowsAppSDK#3622]
### Describe the bug

There would leave a white bar on the top of a window. When it comes to an XAML window, I could wipe that by ExtendsContentIntoTitleBar. However, for the window created by win32 api, there seems to be no corresponding api or a way to transfer it into an XAML window.

### Steps to reproduce the bug

Here's my demo project.
https://github.com/ACGNnsj/WinUI3CppWinRTDemo/blob/3477dedd9404e15689278aa9c2eab734fae20316/OCR/MainWindow.xaml.cpp#LL88C3-L88C8

### Expected behavior

I just want to find a method to erase that white space.
It would be better if there is some way to transfer a native window into an XAML one in a WinUI 3.

### NuGet package version

Windows App SDK 1.3.0: 1.3.230331000

### Packaging type

Packaged (MSIX)

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2022

**Comment by DarranRowe** [comment]
The big thing to remember about AppWindow and the related classes is that these are purely an abstraction of the Windows API HWND. If you look at the results of using OverlappedPresenter.SetBorderAndTitleBar, calling GetWindowLongPtr before and after this call to get the window styles shows a lot.

For a window created with the WS_OVERLAPPED style, calling it before gives the value of 0x04CF0000, this corresponds to the styles of WS_CLIPSIBLINGS | WS_CAPTION | WS_MAXIMIZEBOX | WS_MINIMIZEBOX | WS_SYSMENU | WS_THICKFRAME. After, getting the style gives the value of 0x04070000, this corresponds to the styles of WS_CLIPSIBLINGS | WS_THICKFRAME | WS_MAXIMIZEBOX | WS_MINIMIZEBOX. What this means is that all this is doing is toggling the window styles.

The window looks like the following:
![Screenshot 2023-05-10 152911](https://github.com/microsoft/WindowsAppSDK/assets/52577874/498afc13-050b-45a2-b94c-4f4e6da4078a)

So, this leads to the question, what happens if you just set the styles yourself. Calling SetWindowLongPtr to set the styles with the value of 0x04070000, the window looks like:
![Screenshot 2023-05-10 153318](https://github.com/microsoft/WindowsAppSDK/assets/52577874/ae00c4a8-d792-4d3e-8e73-c04986564e36)

Interesting, right? This means that the bar you are seeing is coming from the underlying Windows API window itself. After messing with the styles a little more, it also seems like it is WS_THICKFRAME which does it. Removing the WS_THICKFRAME style, and then using DwmSetWindowAttribute to re-enable the rounded corners on the window, I have the following:

![Screenshot 2023-05-10 154308](https://github.com/microsoft/WindowsAppSDK/assets/52577874/69c592e8-0cc7-4d0a-9265-75fe19777d22)

Finally, remember that AppWindowTitleBar.ExtendsContentIntoTitleBar is available for desktop applications and doesn't need Xaml to be active in a window.

**Comment by ACGNnsj** [comment]
Many thanks for your explanation! I’ll have a close study on these stuffs.
