### ISSUE TITLE
Unable to display `AppNotification` due to `System.Runtime.InteropServices.COMException` (`0x80070490`): Element not found.

### ISSUE THREAD

**Issue by youk** [microsoft/WindowsAppSDK#3698]
### Describe the bug

I am trying to display a simple notification from PowerShell script. I am getting the following error:

```
ErrorRecord                 : Exception calling "ShowNotification" with "0" argument(s): "Element not found.
                              "
WasThrownFromThrowStatement : False
TargetSite                  : Void ConvertToMethodInvocationException(System.Exception, System.Type, System.String, Int32, System.Reflection.MemberInfo)
Message                     : Exception calling "ShowNotification" with "0" argument(s): "Element not found.
                              "
Data                        : {[System.Management.Automation.Interpreter.InterpretedFrameInfo, System.Management.Automation.Interpreter.InterpretedFrameInfo[]]}
InnerException              : System.Runtime.InteropServices.COMException (0x80070490): Element not found.

                                 at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
                                 at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
                                 at ABI.Microsoft.Windows.AppNotifications.IAppNotificationManagerMethods.Show(IObjectReference _obj, AppNotification notification)
                                 at Microsoft.Windows.AppNotifications.AppNotificationManager.Show(AppNotification notification)
                                 at TestApp.ShowNotification()
                                 at CallSite.Target(Closure, CallSite, Type)
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087
StackTrace                  :    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32
                              numArgs, MemberInfo memberInfo)
                                 at CallSite.Target(Closure, CallSite, Type)
                                 at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
                                 at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
```
I am not sure this is specific to PowerShell as I am getting the same error when run similar C# code in Polyglot Notebooks/VS Code.

Am I doing this right? Is there any way to get more meaningful error message? As far as I can see all required assemblies are present and can be successfully loaded.

### Steps to reproduce the bug

Run the following code in PowerShell Core 7.3.x
```powershell
using namespace Microsoft.Windows.AppNotifications
using namespace Microsoft.Windows.AppNotifications.Builder
using namespace Microsoft.Windows.ApplicationModel.DynamicDependency

using assembly deps\Microsoft.WindowsAppRuntime.Bootstrap.Net.dll
using assembly deps\Microsoft.Windows.AppNotifications.Builder.Projection.dll

[Bootstrap]::Initialize(0x00010003)

[AppNotificationManager]::Default.Show([AppNotificationBuilder]::new().BuildNotification())

[Bootstrap]::Shutdown()
```

### Expected behavior

Notification is displayed.

### NuGet package version

1.3.230602002

### Packaging type

Unpackaged

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Other

### Additional context

```
> winget list WinAppRuntime

Name                                        Id                                                            Version
-------------------------------------------------------------------------------------------------------------------------
WinAppRuntime.Main.1.3                      MicrosoftCorporationII.WinAppRuntime.Main.1.3_8wekyb3d8bbwe   3000.882.2207.0
WinAppRuntime.Singleton                     MicrosoftCorporationII.WinAppRuntime.Singleton_8wekyb3d8bbwe  3000.882.2207.0
Windows App Runtime DDLM 3000.882.2207.0-x6 Microsoft.WinAppRuntime.DDLM.3000.882.2207.0-x6_8wekyb3d8bbwe 3000.882.2207.0
Windows App Runtime DDLM 3000.882.2207.0-x8 Microsoft.WinAppRuntime.DDLM.3000.882.2207.0-x8_8wekyb3d8bbwe 3000.882.2207.0
```

```
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```
> dotnet --info

.NET SDK:
 Version:   7.0.305
 Commit:    98e1b6c381

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.305\

Host:
  Version:      7.0.8
  Architecture: x64
  Commit:       4b0550942d

.NET SDKs installed:
  7.0.305 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by DarranRowe** [comment]
Well, first and foremost, the documentation for [Show](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.windows.appnotifications.appnotificationmanager.show?view=windows-app-sdk-1.3) states that you must call [Register](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.windows.appnotifications.appnotificationmanager.register?view=windows-app-sdk-1.3) first.
It is probably a good idea to look through the [unpackaged AppNotification](https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/Notifications/App/CsUnpackagedAppNotifications) sample to see what this does. Another thing looking through this reveals is that a handler for the NotificationInvoke event has to be registered otherwise a new process will be launched for each notification. Also, adding the handler before the call to Register means that you will handle all notifications.

**Comment by DarranRowe** [comment]
Well, the WinRT projections are actually thinner wrappers around the ABI than you may expect. The C++/WinRT projection is more or less
```
winrt::check_hresult(*ABI call here*);
```
I would expect that along with the extra marshalling needed, the .NET projection isn't that far from this either.
This is where some of the fun problems start. The ABI call itself will only return a HRESULT, a single error code isn't that great for error checking. Since the exception you are seeing originates from the projection (the ABI cannot allow exceptions to escape), it means that it may only have the HRESULT, and the call is long over. This is understandable since the ABI is callable in multiple languages, and you can guarantee that different languages use different exception mechanics. Some languages, like C, don't officially support exceptions.
The other problem is that more complex feedback may end up using functionality like [RoOriginateError](https://learn.microsoft.com/en-us/windows/win32/api/roerrorapi/nf-roerrorapi-rooriginateerror) or [OutputDebugString](https://learn.microsoft.com/en-us/windows/win32/api/debugapi/nf-debugapi-outputdebugstringw). These functions output information to the debugger. As you can imagine, if you don't have a debugger attached to the process then this information will be lost.
There are a few other small things, but to put it simply, the messages don't have to be unhelpful and they may not be unhelpful. It is possible that they are unhelpful though.

**Comment by LegendaryBlair** [comment]
Suggested user to call Registration method first, hence close the issue.
