### ISSUE TITLE
C++ module winrt.ixx dosen't contain "Microsoft.*.h"

### ISSUE THREAD

**Issue by sotanakamura** [microsoft/WindowsAppSDK#3767]
### Describe the bug

C++/WinRT generates C++ module winrt in "winrt.ixx". When it generates C++ projection of Windows App SDK APIs, winrt.ixx should contain "Windows.\*.h" and "Microsoft.\*.h". But, It dosen't contain "Microsoft.\*.h".

### Steps to reproduce the bug

1. Create a project and build it.
2. Open winrt.ixx and you can see it dosen't contain "Microsoft.\*.h".

### Expected behavior

winrt.ixx should contain "Microsoft.\*.h".

### NuGet package version

Windows App SDK 1.3.2: 1.3.230602002

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by DarranRowe** [comment]
This is a C++/WinRT issue.
In Visual Studio, if you set the MSBuild logging and output to diagnostic then you can see what it does. But it basically splits the generation of the projection into 3.
First is the platform projection:
```
2>Target "CppWinRTMakePlatformProjection" in file "C:\Users\Darran\source\repos\Meh\packages\Microsoft.Windows.CppWinRT.2.0.230706.1\build\native\Microsoft.Windows.CppWinRT.targets":
2>  Building target "CppWinRTMakePlatformProjection" completely.
2>  Output file "x64\Debug\Meh.vcxproj.cppwinrt_plat.rsp" does not exist.
2>  Set Property: CppWinRTCommand="C:\Users\Darran\source\repos\Meh\packages\Microsoft.Windows.CppWinRT.2.0.230706.1\build\native\..\..\bin\"cppwinrt %40"x64\Debug\Meh.vcxproj.cppwinrt_plat.rsp"
```
This is where it generates the projections for things in the Windows.* namespaces. This is just a small portion of the log, the full thing contains all of the .winmd references.
Next it generates the reference projections:
```
2>Target "CppWinRTMakeReferenceProjection" in file "C:\Users\Darran\source\repos\Meh\packages\Microsoft.Windows.CppWinRT.2.0.230706.1\build\native\Microsoft.Windows.CppWinRT.targets":
2>  Building target "CppWinRTMakeReferenceProjection" completely.
2>  Output file "x64\Debug\Meh.vcxproj.cppwinrt_ref.rsp" does not exist.
2>  Set Property: CppWinRTCommand="C:\Users\Darran\source\repos\Meh\packages\Microsoft.Windows.CppWinRT.2.0.230706.1\build\native\..\..\bin\"cppwinrt %40"x64\Debug\Meh.vcxproj.cppwinrt_ref.rsp"
```
This is where it generates the projection for any additional references the project makes. This is where it generates the projection for the Windows App SDK for example. Again, this is only a small part of the log since it contains a paths to the .winmd files.
Finally, it generates the projection for your application components:
```
2>Target "CppWinRTMakeComponentProjection" in file "C:\Users\Darran\source\repos\Meh\packages\Microsoft.Windows.CppWinRT.2.0.230706.1\build\native\Microsoft.Windows.CppWinRT.targets":
2>  Building target "CppWinRTMakeComponentProjection" completely.
2>  Output file "x64\Debug\Meh.vcxproj.cppwinrt_comp.rsp" does not exist.
2>  Set Property: _PCH=pch.h
2>  Task "Error" skipped, due to false condition; (('$(CppWinRTOverrideSDKReferences)' != 'true') and ('$(TargetPlatformVersion)' < '10.0.17709.0') and ('$(_PCH)' != 'pch.h')) was evaluated as (('' != 'true') and ('10.0.22621.0' < '10.0.17709.0') and ('pch.h' != 'pch.h')).
2>  Set Property: CppWinRTUsePrefixes=true
2>  Set Property: CppWinRTPrecompiledHeader=pch.h
2>  Set Property: CppWinRTPrecompiledHeader=pch.h
2>  Set Property: CppWinRTCommandUsePrefixes=-prefix
2>  Set Property: CppWinRTCommandPrecompiledHeader=-pch pch.h
2>  Set Property: CppWinRTCommand="C:\Users\Darran\source\repos\Meh\packages\Microsoft.Windows.CppWinRT.2.0.230706.1\build\native\..\..\bin\"cppwinrt %40"x64\Debug\Meh.vcxproj.cppwinrt_comp.rsp"
```
This generates the projection for the components defined in your application/component. This is slightly different from the other two since it also creates default source files for any components defined in your application/component.
Anyway, as you can see, all of these targets are in the Microsoft.Windows.CppWinrt.targets file which is part of the C++/WinRT package.
The winrt.ixx file is also generated by C++/WinRT. The very first line is a comment:
```
// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1
```
So this is why this is the wrong repository to report this.

**Comment by sotanakamura** [comment]
Thank you for providing the information. I did the same thing and I understood the most of the behavior. Anyway, I will move this issue to cppwinrt repo. I think the cppwinrt team responses quickly.
