### ISSUE TITLE
Casting DesktopWindowXamlSource to IDesktopWindowXamlSourceNative fails with E_NOINTERFACE

### ISSUE THREAD

**Issue by litherum** [microsoft/WindowsAppSDK#3978]
### Describe the bug

Casting a `Microsoft::UI::Xaml::Hosting::DesktopWindowXamlSource` to `IDesktopWindowXamlSourceNative` always fails with `E_NOINTERFACE`.

### Steps to reproduce the bug

1. Creating a new Win32 Desktop application from the File -> New Projet wizard
2. Install the latest versions of the Windows App SDK and CppWinRT NuGet packages (which are versions 1.4.231115000 and 2.0.230706.1 respectively),
3. Unload the project, then add `<WindowsPackageType>None</WindowsPackageType>` to the `<PropertyGroup Label="Globals">` section of project file
4. Replace the contents of the main .cpp file with the following:
```cpp
#include "framework.h"
#include "WinUI3XamlIslandsWin32.h"

#include <windows.ui.xaml.hosting.desktopwindowxamlsource.h>
#include <winrt/Microsoft.UI.Dispatching.h>
#include <winrt/Microsoft.UI.Xaml.Hosting.h>
#include <cassert>

int APIENTRY wWinMain(_In_ HINSTANCE hInstance,
                     _In_opt_ HINSTANCE hPrevInstance,
                     _In_ LPWSTR    lpCmdLine,
                     _In_ int       nCmdShow)
{
    winrt::init_apartment(winrt::apartment_type::single_threaded);
    auto dispatcherQueueController = winrt::Microsoft::UI::Dispatching::DispatcherQueueController::CreateOnCurrentThread();
    auto windowsXamlManager = winrt::Microsoft::UI::Xaml::Hosting::WindowsXamlManager::InitializeForCurrentThread();
    winrt::Microsoft::UI::Xaml::Hosting::DesktopWindowXamlSource desktopWindowXamlSource;
    auto interop = desktopWindowXamlSource.as<IDesktopWindowXamlSourceNative>();
    assert(interop != nullptr);
    return EXIT_SUCCESS;
}
```

### Expected behavior

The `desktopWindowXamlSource.as<IDesktopWindowXamlSourceNative>()` cast should succeed, but it actually fails with `E_NOINTERFACE`. Indeed, if you try `winrt::get_interfaces(desktopWindowXamlSource)` to list the interfaces the `DesktopWindowXamlSource` supports, it only lists:

- `IDesktopWindowXamlSource`
- `ICompositionSupportsSystemBackdrop`
- `IClosable`
- `IWeakReferenceSource`
- `ISupportErrorInfo`
- `IUnknown`
- `IInspectable`

### NuGet package version

Windows App SDK 1.4.3: 1.4.231115000

### Packaging type

Unpackaged

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

I've created a sample project at https://github.com/litherum/WinUI3XamlIslandsWin32 demonstrating the problem.

**Comment by DarranRowe** [comment]
All functionality that was on IDesktopWindowXamlSourceNative was moved to other interfaces.
IDesktopWindowXamlSourceNative::AttachToWindow is now [DesktopWindowXamlSource.Initialize](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.hosting.desktopwindowxamlsource?view=windows-app-sdk-1.4).
IDesktopWindowXamlSourceNative::get_WindowHandle is now [DesktopSiteBridge.WindowId](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.content.desktopsitebridge.windowid?view=windows-app-sdk-1.4#microsoft-ui-content-desktopsitebridge-windowid).
IDesktopWindowXamlSourceNative::PreTranslateMessage is now a stand alone function named [ContentPreTranslateMessage](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/win32/microsoft.ui.dispatching.interop/nf-microsoft-ui-dispatching-interop-contentpretranslatemessage).
A couple of notes about using these. First with the fact that Islands are now using [Microsoft.UI.WindowId](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.windowid?view=windows-app-sdk-1.4), this means that you would use GetWindowFromWindowId and GetWindowIdFromWindow to convert between a HWND and a WindowId. For C++, you would include the Microsoft.UI.Interop.h header, you would use the plain version for the rare times that you need the ABI version, or the one in the winrt subdirectory for when you are using C++/WinRT. C# would use the [Win32Interop](https://learn.microsoft.com/en-us/windows/apps/api-reference/cs-interop-apis/microsoft.ui/microsoft.ui.win32interop) class. But IIRC, WinRT interop requires a Windows 10 TFM, to activate, so you would only be able to use this by setting the target version something that includes a Windows 10 version. The WinUI 3 projects default to net6.0-windows10.0.19041.0, so this is probably a good baseline to go for.
Finally, the ContentPreTranslateMessage function is exported from Microsoft.UI.Windowing.Core.dll. This can be a problem for unpackaged applications since it can only be found after you reference the Windows App SDK and referencing the Windows App SDK in an unpackaged application requires that the application loads. This means that a C++ application will either need to set this library as delay loaded when using Microsoft.UI.Dispatching.lib, or you would need to use LoadLibrary/GetProcAddress to use the function. For C#, you would need to use platform invoke right now.

**Comment by litherum** [comment]
Thank you for the detailed reply! It's very helpful.

Is there an example app somewhere where this is all hooked up and working? I've updated the sample app according to your instructions, but it crashes shortly after launch, from deep within `Microsoft.ui.xaml.dll`. (See https://github.com/litherum/WinUI3XamlIslandsWin32/tree/2 for the updated sample app.) Just before crashing, the console prints out:

```
WinRT originate error - 0x80004005 : 'Failed to initialize the application's root visual'.
```

If there's an example somewhere of WinUI 3 working in XAML Islands in a minimal sample app somewhere that I could follow, that would be extremely helpful.

**Comment by DarranRowe** [comment]
The [official sample](https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/Islands) has issues because it has been modified to use the Xaml compiler. If you look at the .vcxproj contents, you should find that it has added the WindowsStore application type. If you don't mind making this type of modification, then it is a viable path, especially since it uses the Xaml compiler and allows you to easily do a lot more. However, this sample does include important information like how to navigate into and out of the island.
If you don't want to make this kind of modification, then the absolute minimum I would recommend is:

[MiniIslandTest.zip](https://github.com/microsoft/WindowsAppSDK/files/13433955/MiniIslandTest.zip)

You can get away without the Application, metadata and resources, but it doesn't look great. The lack of the metadata provider will also limit your use of the [XamlReader](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.markup.xamlreader?view=windows-app-sdk-1.4) class to load Xaml from memory and from file. It also limits the use of custom controls.

**Comment by litherum** [comment]
Thank you so much for your help! I now have WinUI 3 Islands working in my app!
