### ISSUE TITLE
.Net 8 doesn't work out of the box - RID and runtime pack issues

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/WindowsAppSDK#3989]
### Describe the bug

I switched from .Net 7 to 8. And I immediately got 77 errors across my projects. I read that I have to put this in my project files..

    <UseRidGraph>true</UseRidGraph>
    
That's the first issue, if it's required, then please update our project files when we switch to .Net 8. Why should I have to manually put this into my project files. I have to serve myself at the supermarket checkout. Now you want me to write my own project files. Sheesh.

After updating the project files I still have 22 errors...

NETSDK1082 There was no runtime pack for Microsoft.NETCore.App available for the specified RuntimeIdentifier 'win10-arm'

I'm not targeting arm, I never said I was targeting arm. This wasn't an issue in .Net 7.

### Steps to reproduce the bug

...

### Expected behavior

...

### Screenshots

...

### NuGet package version

Windows App SDK 1.4.3: 1.4.231115000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by riverar** [comment]
Dupe of https://github.com/microsoft/WindowsAppSDK/issues/3842, which you also commented in 😂

**Comment by DarranRowe** [comment]
In case it is required to completely spell it out, the reason why the Windows App SDK doesn't work out of the box with .NET 8 is because the Windows App SDK doesn't officially support .NET 8.
Official support would be part of the release notes, as an example, the [release notes for 1.2](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#version-12-1) states:
"When released, WinAppSDK 1.2 will support .NET 7 as well."
The 1.4 release notes were also quite clear in the [known issues](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#known-issues). It outright stated:
"Because of this issue and because .NET 8 has not officially released yet, the Windows App SDK 1.4 does not officially support .NET 8."
So the simple answer to the question of why do you have to manually edit the project file is you are using things in an unsupported way, and this is a workaround. The Windows App SDK releases have also been pretty consistent in that the servicing releases has been for bug fixes only. There was only ever one exception as far as I know, and that was multi windowing support coming with 1.0.1.
Other people may feel differently, but I was personally expecting .NET 8 support to come along with the 1.5 release.

**Comment by Gavin-Williams** [comment]
I'm not working toward supporting ARM devices either yet. So any code that suggests so was probably put there by Visual Studio's project code system.
