### ISSUE TITLE
StorageLibraryChangeReader.GetLastChangeId missing ?

### ISSUE THREAD

**Issue by christosk92** [microsoft/WindowsAppSDK#4431]
### Describe the bug

I am trying to port a UWP app to WinAppSdk but I am hitting a roadblock:

Is it true that the StorageLibraryChangeReader.GetLastChangeId Method is missing for WinAppSdk?
It's available in UWP:
https://learn.microsoft.com/en-us/uwp/api/windows.storage.storagelibrarychangereader.getlastchangeid?view=winrt-22621

### Steps to reproduce the bug

1. Have a StorageLibrary object
2. Create a ChangeReader: `var changeReader = changeTracker.GetChangeReader();`
3. Try to invoke: `ulong lastChangeId = changeReader.GetLastChangeId();`

### NuGet package version

Windows App SDK 1.5.3: 1.5.240428000

### Packaging type

Packaged (MSIX)

**Comment by DarranRowe** [comment]
What do you mean missing?
It is documented to only be available for desktop versions of Windows starting with Windows 11. This means that you need to build using the Windows 11 or newer versions of the Windows SDK or using the Windows 11 TFM. This also means that if you try running on Windows 10, it will fail to call.

Since StorageLibraryChangeReader is under the Windows root namespace (Windows.Storage.StorageLibraryChangeReader), it means that this is a Windows built in component and you should be looking at the Windows side of things and not the Windows App SDK side of things.

**Comment by christosk92** [comment]
> [DarranRowe](/DarranRowe)

1. I mean missing as in: My app will not compile if i do GetLastChangeId(). Autocomplete also does not show the method.
2. I am aware of the Windows 11 requirement. I already have a check in place: ` if(ApiInformation.IsMethodPresent(typeof(StorageLibraryChangeReader).FullName, "GetLastChangeId"))`
3. 
![image](https://github.com/microsoft/WindowsAppSDK/assets/13438702/9770b3cd-30a8-4f38-851e-ebb3f3f1adb1)

**Comment by DarranRowe** [comment]
Then, since you didn't mention it, do you have the Target OS version set to at least Windows 11 (version 10.0.22000.0) in the project properties? You need to target Windows 11 so the compiler is able to find the definitions even if you intend to run it on Windows 10.
