### ISSUE TITLE
Handle '----' better and enforce having a space before it.

### ISSUE THREAD

**Issue by aeloros** [microsoft/WindowsAppSDK#907]
It depends. If the command line is

```
----a:b"c\"d"e
```

is the expected parse
1. contract = `a`, data = `b"c\"d"e`; or
2. contract = `a`, data = `bc"de`
CommandLineToArgvW will give you version 2.

Also, it seems that a space is not required before the first dash, so we will treat

```
contoso.exe hello----dolly.txt
```

as
* contract = `dolly.txt`, data = empty

which could be surprising if somebody has a file named "hello----dolly.txt".

_Originally posted by @oldnewthing in https://github.com/microsoft/ProjectReunion/pull/823#r638450800_

**Comment by aeloros** [comment]
Make sure to write tests to validate command-line behaviors.

**Comment by oldnewthing** [comment]
Even a space before the dash isn't good enough. The user might have a file called `"hello  --dolly.txt"` and launching it will pass the command line `contoso.exe "hello ---dolly.txt"` and since we don't track quotation marks, we think that the space before the dashes is a command line operation separator when in fact it's part of an enclosing file name.

**Comment by aeloros** [comment]
Address these items as part of this issue.

https://github.com/microsoft/WindowsAppSDK/pull/823#discussion_r647738627
https://github.com/microsoft/WindowsAppSDK/pull/823#discussion_r647720668
