### ISSUE TITLE
Proposal: Allow .appinstaller file to help uninstall optional packages

### ISSUE THREAD

**Issue by harvinders** [microsoft/WindowsAppSDK#94]
# Proposal: Allow .appinstaller file to help uninstall optional packages

## Summary

Currently `.appinstaller` file can be used to install optional/dependent packages. It can also be used to install additional packages if required by publishing an updated `.appinstaller` file. However it is not possible to use this method to uninstall an already installed optional/dependent package.

## Rationale

* Allow developers to push special functionality to the users, which can later be uninstalled. Think COVID situation, lot of us would like to do the right thing and offer a limited time functionality. 
* Though there are other ways to disable the features at the later date, this would allow developer to do a clean uninstall.

## Scope

| Capability | Priority |
| :---------- | :------- |
| Allow developers to do a clean uninstall of optional/dependent packages| Must |

## Open Questions

Should something similar be allowed for the store published apps?

**Comment by cwruss** [comment]
Thanks for the feedback and trying to do the right thing. Removing content as part of a background update can appear as data loss since the user may have no warning that the feature is being removed and suddenly it is gone. This appears to be an uncommon scenario and could be achieved by removing the optional package using runtime code. Is there a strong reason why it needs to be supported as part of the .appinstaller file that we are not thinking of?

**Comment by cwruss** [comment]
Thanks again for the feedback. We are closing this issue as there is not a high customer demand for this scenario. If you believe this is still an issue, please open a new issue with the compelling customer scenario and we can consider it.
