### ISSUE TITLE
MddBootstrapInitialize returns ERROR_NO_MATCH unexpectedly

### ISSUE THREAD

**Issue by riverar** [microsoft/WindowsAppSDK#949]
Consider the scenario:
* my app is looking for the Project Reunion 0.3-preview framework package
* my app is okay with any minor version of the framework package found (0.1-preview and above)
* I have the Project Reunion 0.8-preview x86 and x64 runtimes installed

I write the following code:

```cpp
#include <iostream>
#include <windows.h>
#include "MddBootstrap.h"

int main()
{
    PACKAGE_VERSION minimum_version{};
    minimum_version.Minor = 1;

    const uint32_t requested_version{ 0x00000003 };
    HRESULT hr = MddBootstrapInitialize(requested_version, L"preview", minimum_version);

    std::cout << "MddBootstrapInitialize returned " << std::hex << hr << std::endl;
 }
```

## Expected
`MddBootstrapInitialize` to load the framework package bits into my process and return `ERROR_SUCCESS`.

## Actual
`MddBootstrapInitialize` unexpectedly returns `ERROR_NO_MATCH`.

## Versions
Windows 10 19043.1052
ProjectReunion-0.8Preview-Install*.exe runtimes

**Comment by huichen123** [comment]
requested_version would be 0x00000008. there is no 0.3-preview, but 0.8-preview. :)

**Comment by riverar** [comment]
@huichen123 But it's my understanding this is a _search_ API. Why is that precision needed if I've already gave the API a minimum?

**Comment by DrusTheAxe** [comment]
0.3 lacks the infrastructure needed to satisfy the Bootstrap API (ditto 0.5).

Under the covers the Bootstrap API uses Dynamic Dependencies so it requires the Main and DDLM MSIX packages, and those didn't exist before 0.8

**Comment by riverar** [comment]
Ah, makes sense.

Thanks @huichen123 @DrusTheAxe for the quick handling. Can close as needed.

**Comment by riverar** [comment]
@DrusTheAxe So, shouldn't the search, given the above parameters, still locate 0.8 on the machine?

**Comment by riverar** [comment]
OK, after a bit more digging, it appears the [expected usage](https://github.com/microsoft/ProjectReunion/blob/main/specs/dynamicdependencies/DynamicDependencies.md#54-packaging---projectreuniondll-projectreunionbootstrapdll-and-ddlm) is `MddBootstrapInitialize(installed_ddlm_version, ..., minimum_framework_version)`. Mdd will then attempt to locate the **exact** DDLM version and only _then_ try to find a best matching framework.

https://github.com/microsoft/ProjectReunion/blob/a1a64e8e24c91266968b98f4352673b2b490cc7c/dev/ProjectReunion_BootstrapDLL/MddBootstrap.cpp#L263-L279

I'm trying to build Project Reunion samples that call `MddBootstrapInitialize` but with this behavior, they will all fail if the user has a older/newer DDLM package installed.

So I'm a bit puzzled as to how app developers will write/distribute a durable app that utilizes this API. Is Microsoft going to accumulate DDLM versions and bundle all previous releases in the runtime redistributables?

**Comment by DrusTheAxe** [comment]
>I'm a bit puzzled as to how app developers will write/distribute a durable app that utilizes this API

Specify the release you desire, i.e. the release's Major.Minor version and Channel. You can also specify a minimum build within a release. For example to use any build of Microsoft.ProjectReunion 0.8 Preview

```
UINT32 majorMinorVersion{ 0x00000008 };
auto versionTag{ L"preview" };
PACKAGE_VERSION minVersion{};
MddBootstrapInitialize(majorMinorVersion, versionTag, minVersion)
```

Or specify a higher minVersion (the above is 0.0.0.0) to require a certain minimum build of 0.8-preview. See `<Identity...Version=...>` in `appxmanifest.xml` for any of the MSIX for the exact MSIX version.

As the Bootstrap API is parameter driven it works for all releases of WindowsAppSDK.


BTW I tried updating the build to generate a header with this info so you could write e.g.

```
MddBootstrapInitialize(PROJECTREUNION_VERSION_MAJORMINOR, PROJECTREUNION_VERSION_VERSIONTAG, PROJECTREUNION_VERSION);
```

and you'd use whatever version you'd compiled with. But something was off in the build pipeline, generating the file just fine but didn't get carried along to the NuGet. Something I hope to get back to soon.



>with this behavior, they will all fail if the user has a older/newer DDLM package installed

If by older/newer you're referring to the release Major.Minor and/or VersionTag then yes, they don't qualify. If the Microsoft.ProjectReunion.1.0-preview1 package is installed it's only relevant if you call `MddBootstrapInitialize` looking for 1.0-preview1. It's irrelevant if you ask for 0.8-preview. After all, if you're built for 0.8 then (hypothetical) 0.7 and 0.9 are distinct things that won't satisfy your needs. You'd need to change to build with a 0.9 release to run with a 0.9 release, and ditto you'd need to change your build from 0.9-preview to 0.9 (stable) to run with 0.9 (stable).

Once we've found packages in the specified Major.Minor-VersionTag we further narrow the list to packages with the same architecture as the caller e.g. your x86 dll won't match x64 or arm64 packages, only x86.

Next step is to ignore packages whose (MSIX) version number is less than the `MddBootstrapInitialize(...minVersion)` parameter. Thus the Framework package version 1.2.3.4 is ignored if you specify minVersion=1.2.3.5.

We apply some additional checks, e.g. if a package passes all the above criteria but its package status indicates it's Tampered or NotAvailable or otherwise not-OK then it's not usable at the moment and ignored.

If we have no remaining candidates we return an error.
If we have 1 candidate then yay! We use it.
If we have >1 candidate we pick the best one (typically meaning the highest version) and use that.

This is why your call got ERROR_NO_MATCH. You were asking for 0.3-preview and there are no matching 0.3 candidates (because there's no DDLM, because DDLMs don't exist for 0.3).

There's more details in [the Dynamic Dependencies spec](https://github.com/microsoft/WindowsAppSDK/blob/main/specs/dynamicdependencies/DynamicDependencies.md).


>Is Microsoft going to accumulate DDLM versions

Astute question. No. We've accounted that. And thus was born `MddLifetimeManagementGC()`, which knows how to enumerate redundant DDLM packages and remove them.

Guidance to developers deploying Project Reunion MSIXs is to install them and not explicitly uninstall (just because YOU installed v1.2.3.4 and are done with it doesn't mean everyone else is). Thus, `MddLifetimeManagementGC()`.

If you specify `minVersion=1.2.3.4` you're specifying a minimum required version. A 'floor' for acceptable version. There is no `maxVersion` i.e. no upper bound (no 'ceiling'). Thus if you specify `minVersion=1.2.3.4` you're guaranteed not to get 1.2.3.3, but you could get 1.2.3.5.

If you install 1.2.3.0 thru 1.2.3.9 you'd have 10 DDLM packages (per architecture). But 1.2.3.9 will satisfy anyone looking for 1.2.3.0 thru 1.2.3.8 and thus can be removed (GC'd).

Take a look at `dev/DynamicDependency/MddLifetimeManagement.cpp` if you're interested in more details regarding the algorithm.

The one gap is a maintenance task. The API exists but needs to be called semi-regularly. That's one of the reasons I've been closely watching [Do resource intensive work opportunistically to reduce interference with user applications #621](https://github.com/microsoft/WindowsAppSDK/issues/621) as it would provide the ideal mechanism to call this (and it sounds really cool in its own right :-). But as that's not currently on the roadmap I expect to make a BackgroundTask to do the GC on a recurring basis, until #621 is addressed.

>and bundle all previous releases in the runtime redistributables?

If you're asking if e.g. the installer will install version 0.3, 0.5, 0.8, 1.0, 1.1, 1.2, ... then no. <del>ProjectReunionInstaller.1.0.exe</del>WindowsAppSDKInstaller.1.0.exe ;-) will install 1.0 packages. It won't install 0.8 or 1.1 packages.

Let's say 1.0 has 3 patch releases (i.e. 1.0.0, 1.0.1 and 1.0.2). The 1.0.0 installer will install 1.0.0 packages. The updated 1.0.1 installer will install the 1.0.1 packages, and the newer 1.0.2 installer will install the 1.0.2 packages. But that's OK. The 1.0.2 Framework and Main packages will be installed and supersede the 1.0.0 and/or 1.0.1 packages (if present). The DDLM is the unusual case. If you install 1.0.0, then 1.0.1 and 1.0.2 you'll end up with the 1.0.2 Framework package, the 1.0.2 Main package, and the 1.0.0 + 1.0.1 + 1.0.2 DDLM packages.

That's a bit simplistic as we ignored architecture. Assuming ARM64 where arm64 + x86 + x64 packages are supported it's...

Run WindowsAppSDKInstaller-1.0.0.exe
==> Packages installed: Fwk-1.0.0[x86+x64+arm64], Main-1.0.0[arm64], DDLM-1.0.0[x86+x64+arm64]
Run WindowsAppSDKInstaller-1.0.1.exe
==> Packages installed: Fwk-1.0.1[x86+x64+arm64], Main-1.0.1[arm64], DDLM-1.0.0[x86+x64+arm64], DDLM-1.0.1[x86+x64+arm64]
Run WindowsAppSDKInstaller-1.0.2.exe
==> Packages installed: Fwk-1.0.2[x86+x64+arm64], Main-1.0.2[arm64], DDLM-1.0.0[x86+x64+arm64], DDLM-1.0.1[x86+x64+arm64], DDLM-1.0.2[x86+x64+arm64]
Run maintenance task calling MddLifetimeManagementGC()
==> Packages installed: Fwk-1.0.2[x86+x64+arm64], Main-1.0.2[arm64], DDLM-1.0.2[x86+x64+arm64]

Packages could hang around a bit longer if apps are running using them but that's fine. We'll remove unnecessary packages over time, eventually coalescing to the minimal required set.

I hope this answers your questions. 

And, yes. If your head hurts reading all this then don't worry -- you're in good company. It makes my head hurt too :P

This is one of the more complex areas of the project. We're weaving a delicate dance to make existing Windows releases do what we need _without_ changing Windows AND posing minimal impact to the developer (you :-). It relies on designs and behaviors that aren't obvious at first blush, and to some extent requires a deep understanding of the deployment stack to see how all the dots connect in a stable way. We've tried to bury the complexity inside WindowsAppSDK and make it our headache ;- so you don't need to sweat the intricacies and can just use <del>ProjectReunion</del>WindowsAppSDK. I think we've managed to pull it off.

But more importantly, what do _you_ think?

**Comment by riverar** [comment]
Appreciate the brain dump. We're on the same page.

My question regarding the accumulation of DDLM versions was not so much in concern for the user's machine but rather in concern for the developer. Because the `MddBootstrapInitialize` function **does not** support specifying a minimum version of the DDLM itself, users must install every single version of the DDLM component to satisfy app requirements.

This sounds like another vcredist. (Or there will be an ever growing runtime package that bundles all released versions--major and minor!--of the DDLM component.)

Did I understand that correctly?

**Comment by DrusTheAxe** [comment]
>users must install every single version of the DDLM component to satisfy app requirements

Not really.

Let's say Spotify is an unpackaged app built with WindowsAppSDK 1.0.1. It will need 1.0.1+, as in, 1.0.* where * is >= 1.

Spotify's installer should ensure WindowsAppSDK >=1.0.1 is installed, and if not it should install WindowsAppSDK 1.0.1. That includes the Framework, Main and DDLM packages (consider this a set, just like one would install the Visual Studio 2015 runtime via the vc_redist.x64.exe for the Visual C++ Redistributable for Visual Studio 2015 and not just some of its content).

Spotify doesn't use 1.1 so it doesn't care if 1.1(.anything) is on the machine or not.

OTOH Telegram needs WindowsAppSDK 1.1.2. Thus it needs WindowsAppSDK 1.1.2+ installed (i.e. 1.1.* where * is >= 2). Telegram doesn't care about 1.0 (or 1.2, or anything other than 1.1).

Of course if you install Telegram and not Spotify you don't need both versions installed, just 1.1. Regardless the universe of possible WindowsAppSDK releases.

This is no different than if, say, Spotify and Telegram need different releases of the VS runtime. Or for an example closer to home, if Spotify used WinUI 2.3 and Telegram used WinUI 2.4 you'd need both WinUI 2.3 and 2.4 framework packages installed if you have Spotify and Telegram installed.


>Because the MddBootstrapInitialize function does not support specifying a minimum version of the DDLM itself

It doesn't need to, because you specify the EXACT version of the WindowsAppSDK release you want via the `majorMinorVersion` parameter:

1. By calling the API we know you're talking about WindowsAppSDK
2. By specifying the majorMinorVersion parameter we know which version of you're talking about (1.0, 1.1, etc)
3. By specifying the versionTag parameter we know which channel you're talking about (experimental, etc)
4. By specifying the minVersion parameter we know the oldest build within that version you require

Thus...

* The Framework+Main packages include 1+2+3 in their package Name.
* The DDLM's appExtension advertises itself with 1+2+3 so `MddBootstrapInitialize` can find the set of potential candiates.
* The DDLM's appExtension's data includes the minVersion of the Framework package so given a set of appExtensions matching 1+2+3 we can narrow down to which also meets 4.

The reason the Framework+Main package's Name only includes 1+2+3 but the DDLM's package Name is unique to the individual build and architecture is for one reason: servicing.

This is one of the complex facets. My apologies if you're already familiar with this information but most aren't so let's take a half step back to clearly paint the picture. To help keep things sane ;-) we'll call the MSIX packages WASfwk, WASmain and WASddlm.

A core rule of MSIX is a user can only have 0-1 Main package in a package family registered (aka installed) at the same time. If you install WASmain 1.0.0.0 then install 1.0.0.1 you will be _updated_ to 1.0.0.1. A user can't have both 1.0.0.0 and 1.0.0.1 registered at the same time. Likewise, a user can't have 1.0.0.0 x86 _and_ 1.0.0.0 x64 registered at the same time. When it comes to Main packages you can only have 1 in the package family registered at a time.

Another core rule of MSIX is this differs for Framework packages. A user can have MANY Framework packages in a family registered at the same time. Not only can a user have WASfwk 1.0.0.0 x86 and 1.0.0.0 x64 registered at the same time but it's common to see this. A user can _also_ have 1.0.0.1 registered. And 1.0.0.2, 1.0.1.0, 1.1.0.0, ... And there's  very important reason for it -- servicing packages while in use. When we have an update for a Framework package we apply it in a non-impactful way e.g. if WASfwk 1.0.0.0 is registered and in use by foo.exe and you `Add-AppxPackage WASfwk-1.0.0.1.msix` the Deployment stack does a few things...

* We add WASfwk to the system e.g. its package directory is created based on its unique package full name e.g. `%ProgramFiles%\WindowsApps\WASfwk_1.0.0.1_x64__1234567890abc`
* Any Main package dependent on WASfwk **and not in use** has its definition changed to point to 1.0.0.1
* Any Main package dependent on WASfwk **and in use** has its definition unchanged (still points to and uses 1.0.0.0), but it's marked "update dependency at next opportunity".
* If/when WASfwk has no Main package dependent on it the Deployment stack removes (deletes) WASfwk

"in use" means "are there 1+ process running with this package's identity for this user". Thus if e.g. Outlook is running and using WASfwk 1.0.0.0 then we'll add WASfwk 1.0.0.1 to the system but Outlook stays up and running, using 1.0.0.0.

"update dependency at next opportunity" means when the last process for that user/package ends, we change its definition to point to 1.0.0.1. Thus when I quit Outlook it's definition is changed so the next time I run Outlook it uses 1.0.0.1.

That last bullet about removing (deleting) WASfwk 1.0.0.0 happens when WASfwk 1.0.0.1 is installed if no one on the machine needs 1.0.0.0 anymore, i.e. immediately. If someone does need it (e.g. Outlook is running using it), it's left alone for now. Later when things change and 1.0.0.0 is no longer needed it'll be removed (deleted).

NOTE: This is a slightly simplified but quick explanation. There's additional factors that can come in to play e.g. [DeploymentOptions.ForceTargetApplicationShutdown](https://docs.microsoft.com/uwp/api/Windows.Management.Deployment.DeploymentOptions?view=winrt-20348) but this is thhe relevant core of the matter for purposes of this discussion.

"But wait! WASfwk 1.0.0.1 can be added while apps are running but how's it work if we can't have both WASmain 1.0.0.0 and 1.0.0.1?"

The answer's simple - we don't use WASmain for any length of time. If it's used, it's for very short windows of time and nothing impactful if we happen to get lucky and need to update it. Thus you can specify [DeploymentOptions.ForceTargetApplicationShutdown](https://docs.microsoft.com/uwp/api/Windows.Management.Deployment.DeploymentOptions?view=winrt-20348) and if WASmain happens to be in use the the process will be terminated and the install merrily proceeds. So you might have WASfwk 1.0.0.0 and 1.0.0.1 registered but you'll only have WASmain 1.0.0.1 (and anything it does/will-do is backwards compatible it any apps using WAS 1.0.0.0 are fine).

"But isn't WASddlm used by long-running processes? Did you say it's a Main package and Main packages don't support side-by-side/concurrent install behavior like Framework packages?"

Yes. And this is how we get to the DDLM's unusual naming scheme.

Yes, WASddlm is a Main package, so yes, you can only have 0-1 of them in a package family registered for a user.

But there's only 1 DDLM package in any DDLM package family.

Whereas Main packages have package family names like `Microsoft.WindowsCalculator_8wekyb3d8bbwe` or `Microsoft.ProjectReunion.0.8-preview_8wekyb3d8bbwe`, the DDLM packages include the architecture and full MSIX version number e.g. `Microsoft.ProjectReunion.DDLM.8000.146.628.0-a6-p__8wekyb3d8bbwe`. No 2 builds have the same identity, thus we honor the "0-1 Main in package family" rule. Every package has a unique package family name and despite they may have similar spelling ;-) they're not the identical package family name so they're not the same package family.

This is also why if you update a Main package through 100 updates and you'll still only have 1 package installed whereas if you updated WindowsAppSDK 100 times you'll have 1 WASmain but 100 WASddlm (on x86, more on other cpus that support more architectures). We don't actually need 100 WASddlm for WindowsAppSDK 1.0. We just need the highest version (as it's backwards compatible so anyone needed WASddlm 1.0.0.0 would be equally satisfied using 1.0.0.100). But the standard Deployment mechanisms to identify unneeded packages doesn't cover us here. This is where `MddLifetimeManagementGC()` comes in.

There's one more related but subtle detail to note. Let's say you install WindowsAppSDK 1.0.0.0 and then 1.0.0.1 but some apps are using 1.0.0.0. We'll wind up with...

* WASfwk 1.0.0.0 + 1.0.0.1
* WASmain 1.0.0.1
* WASddlm 1.0.0.0 + 1.0.0.1

WASmain 1.0.0.1's `appxmanifest.xml` declares `<PackageDependency Name="WindowsAppSDK" MinVersion="1.0.0.1"...>` and when installed has that dependency (criteria) resolved to be dependent (point to) 1.0.0.1.

WASddlm 1.0.0.1 likewise declares `<PackageDependency Name="WindowsAppSDK" MinVersion="1.0.0.1"...>` and when installed has that dependency (criteria) resolved to be dependent (point to) 1.0.0.1.

WASddlm 1.0.0.0 while declared `<PackageDependency Name="WindowsAppSDK" MinVersion="1.0.0.0"...>` (1.0.0.0!)and when installed had that dependency (criteria) resolved to be dependent (point to) 1.0.0.0. But it was in use so this wasn't changed.

Later (when it's no longer in use) that dependency is reevaluated. We see WASfwk 1.0.0.0 and 1.0.0.1 can satisfy the dependency, so we pick the higher version. WASddlm 1.0.0.0 now points to WASfwk 1.0.0.1. If someon were to use WASddlm 1.0.0.0 that's fine...and they're get WASfwk 1.0.0.1!

After all, we guaranteed to meet their minimum required version, not that we wouldn't use a higher compatible version. And the rule of Framework packages is a Framework package is backwards compatible with older versions in its package family. As WASfwk 1.0.0.0 and 1.0.0.1 share the same package family name and WASddlm requires >= 1.0.0.0 both are equally valid candidates to satisfy the `<PackageDependency>`. And given multiple matching candidates, we'll choose the highest version.

Thus it's possible you could have WASddlm 1.0.0.0, 1.0.0.2 and 1.0.3.0 installed but all could be using WASfwk 1.0.3.0.

That's also why Deployment could in that case remove WASFwk 1.0.0.0 and 1.0.0.2 - once there's package dependencies resolved to 1.0.0.0 **including WASddlm's dependency on WASfwk** we can remove WASfwk 1.0.0.0. And ditto for 1.0.0.2.

So just because you install multiple updates of WindowsAppSDK major.minor (and thus multiple WASfwk + WASmain + WASddlm), you will (sooner or later) only need 1 WASmain + 1 WASfwk per architecture + 1 WASddlm per architecture. The deployment stack removes the older WASmain + WASfwk packages, and `MddLifetimeManagementGC()` removes the older WASddlm packages.

Of course packages are registered and tracked on a machine per-user, but physically stored once and shared across all users on the machine. That's why _you_ may not need a specific package anymore but it can't be removed until ALL users on the machine don't need it. Users have their dependencies updated sooner if possible or later if necessary (worst case is typically at next login). This is why when you install a newer version of a Framework package all dependencies across all users on a machine may not be immediately updated to the latest version, but they will coalesce to the latest over time.

So that's why DDLM packages have such unusual naming, why they don't block servicing and why they don't multiply over time to consume all available disk space :-)

My apologies if it's a lot of information but it's a complex and subtle dance with a lot of interlocking parts. It's hard to pull out an isolated thread and understand how it works and why without getting at least a glimpse of the tapestry.


>This sounds like another vcredist.

A runtime needed by your app? Yes. And there's work being done to make that easy and convenient (using MSIX, providing the [installer](https://github.com/microsoft/WindowsAppSDK/issues/443), etc).

Do you consider this a good thing or bad?

**Comment by riverar** [comment]
Thanks for the background.

> Do you consider this a good thing or bad?

No opinion, really. I understand it's a byproduct of machine-wide deployment and servicing and have made peace with it. (I've also been using it since 0.8 so have warmed up to it.)

What troubles me is that we've got just a few months left and still no specs/comms on:
* how the no-runtime-found experience will look
* what these runtimes will even be called (there are murmurs of putting SDK in the name, which is a terrible idea)
* where users will get these runtimes
* servicing schedule/procedure (assuming users will have to turn on Microsoft Update in the OS?)

**Comment by DrusTheAxe** [comment]
> (I've also been using it since 0.8 so have warmed up to it.)

👍 


>specs/comms on

Great set of questions. They span diverse topics so answers vary. Here goes...

> * how the no-runtime-found experience will look

Could you elaborate on what you mean by 'no-runtime-found experience'? It's unclear if you're referring to AppLocal scenarios, runtime deployment/install scenarios or something else.

> * what these runtimes will even be called (there are murmurs of putting SDK in the name, which is a terrible idea)

See [3. Package Naming](https://github.com/microsoft/WindowsAppSDK/blob/main/specs/Deployment/MSIXPackages.md#3-package-naming)

> * where users will get these runtimes

As in runtime deployment/install scenarios?

> * servicing schedule/procedure (assuming users will have to turn on Microsoft Update in the OS?)

+@andrewleader for questions regarding schedules and process

**Comment by riverar** [comment]
> Could you elaborate on what you mean by 'no-runtime-found experience'? It's unclear if you're referring to AppLocal scenarios, runtime deployment/install scenarios or something else.

User downloads widgets.exe, it tries to bootstrap but fails. _Now what?_ Will bootstrap have localized UI for us to leverage (similar to .NET) or do we need to handle that? (We still need a permanent runtime URL, potentially for each runtime version(?), to point users to.)

> See 3. Package Naming
Users won't see those, hopefully. I'm asking more about what will be in docs/in the error message that appears (see above). I hope we're not planning to tell users "This app requires Microsoft.WindowsAppRuntime.1.0-experimental1".

**Comment by riverar** [comment]
There's no dialog coming at this point, judging by 1.0 branch. Closing as there's nothing left to do here.
