### ISSUE TITLE
Can't build VSIX due to Project.Reunion.nuget.internal references

### ISSUE THREAD

**Issue by riverar** [microsoft/WindowsAppSDK#962]
Steps to reproduce:
1. Clone repository
2. Navigate to `\dev\VSIX`
3. `nuget restore`
4. Observe authentication attempts to internal-only source

```
Generating MSBuild file C:\Sources\ProjectReunion\dev\VSIX\BuildOutput\obj\\WinUI.UWP.CppWinRT.BlankApp\WinUI.UWP.CppWinRT.BlankApp.csproj.nuget.g.props.
Generating MSBuild file C:\Sources\ProjectReunion\dev\VSIX\BuildOutput\obj\\WinUI.UWP.CppWinRT.BlankApp\WinUI.UWP.CppWinRT.BlankApp.csproj.nuget.g.targets.
Writing assets file to disk. Path: C:\Sources\ProjectReunion\dev\VSIX\BuildOutput\obj\WinUI.UWP.CppWinRT.BlankApp\project.assets.json
Restore completed in 423.02 ms for C:\Sources\ProjectReunion\dev\VSIX\ProjectTemplates\UWP\CppWinRT\BlankApp\WinUI.UWP.CppWinRT.BlankApp.csproj.
    [CredentialProvider]Using the ADAL UI  flow for uri https://pkgs.dev.azure.com/microsoft/ProjectReunion/_packaging/Project.Reunion.nuget.internal/nuget/v3/index.json. User sign-in required in a pop-up authentication window.
    [CredentialProvider]DeviceFlow: https://pkgs.dev.azure.com/microsoft/ProjectReunion/_packaging/Project.Reunion.nuget.internal/nuget/v3/index.json
[...]
```

**Comment by BenJKuhn** [comment]
In this case, the issue is that the VSIX needs to embed the App SDK nuget packages in the VSIX itself. Our builds are chained together in such a way that it can pick up the latest build of the Nuget from the internal feed to embed the in-development version corresponding to the same build / version using the internal feed that you're seeing. 

You should be able to override the $(RestoreSources) on the msbuild command line and force it to restore the required packages from a local folder. Take a look at line 6 here to see what I'm referring to.
https://github.com/microsoft/WindowsAppSDK/blob/f05b0d0d7a7fefbfdad590c4e72fe463e052d426/dev/VSIX/Directory.Build.props

We'd eventually like to have a fully supported local "dev machine" build workflow for both Microsoft and external contributors, and that's in my backlog.
